#!/usr/bin/env python3
"""Run the complete reproducibility workflow in the required order.

The runner does not alter analytical settings. It only orchestrates the
repository scripts, records logs, and optionally checks the generated outputs.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import platform
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from typing import Any

ROOT = Path(__file__).resolve().parent
LOG_DIR = ROOT / "run_logs"
STATE_FILE = LOG_DIR / "workflow_state.json"

PYTHON_PACKAGES = {
    "numpy": "numpy",
    "pandas": "pandas",
    "scipy": "scipy",
    "statsmodels": "statsmodels",
    "sklearn": "scikit-learn",
    "matplotlib": "matplotlib",
    "shap": "shap",
}

R_PACKAGES = [
    "data.table",
    "digest",
    "dplyr",
    "ggalluvial",
    "ggplot2",
    "glmmTMB",
    "gridExtra",
    "jsonlite",
    "MASS",
    "Matrix",
    "mgcv",
    "patchwork",
    "R.utils",
]

# Explicit order is important because later scripts verify and reuse outputs
# generated by earlier steps.
WORKFLOW: list[dict[str, Any]] = [
    {"id": "01.01", "group": "descriptive", "kind": "R", "script": "01_Temporal_patterns/temporal_patterns.R", "name": "Temporal patterns"},
    {"id": "02.01", "group": "descriptive", "kind": "R", "script": "02_FAI_season_delineation/fai_season_delineation.R", "name": "FAI fire-season delineation"},
    {"id": "03.01", "group": "descriptive", "kind": "python", "script": "03_FRP_trends/analyze_frp_trends.py", "name": "FRP trends"},
    {"id": "04.01", "group": "descriptive", "kind": "python", "script": "04_Country_season_trends/analyze_country_season_trends.py", "name": "Country-season trends"},
    {"id": "05.01", "group": "descriptive", "kind": "python", "script": "05_Atmospheric_circulation/atmospheric_circulation_analysis_and_figures.py", "name": "Atmospheric-circulation analysis"},
    {"id": "06.01", "group": "descriptive", "kind": "python", "script": "06_EHSA_country_table/make_ehsa_supplementary_table.py", "name": "EHSA country table"},
    {"id": "07.01", "group": "descriptive", "kind": "python", "script": "07_Admin1_hotspot_recurrence/summarize_admin1_hotspot_recurrence.py", "name": "Administrative-region hotspot recurrence"},

    {"id": "08.01", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/01_count_response_and_predictor_audit.py", "name": "Count-response and predictor audit"},
    {"id": "08.02", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/02_compare_single_stage_count_families.py", "name": "Count-family comparison"},
    {"id": "08.03", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/03_compare_single_stage_nb1_configurations.py", "name": "NB1 configuration comparison"},
    {"id": "08.04", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/04_compare_nb1_hurdle_zinb.py", "name": "NB1, hurdle, and ZINB comparison"},
    {"id": "08.04b", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/04b_formalize_count_structure_selection.py", "name": "Formal count-structure selection"},
    {"id": "08.05", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/05_refine_component_specific_predictors.py", "name": "Component-specific predictor refinement"},
    {"id": "08.06", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/06_audit_panel_dependence_and_clustered_inference.py", "name": "Panel-dependence audit"},
    {"id": "08.06b", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/06b_fit_full_data_models_and_two_way_cluster_inference.py", "name": "Full-data fits and clustered inference"},
    {"id": "08.06c", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/06c_audit_parameter_identifiability_and_stabilize_inference.py", "name": "Parameter-identifiability audit"},
    {"id": "08.06d", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/06d_finalize_stable_fixed_effect_inference.py", "name": "Final stable regression inference"},
    {"id": "08.07", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/07_run_regression_spatial_block_validation.py", "name": "Regression spatial-block validation"},
    {"id": "08.08", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/08_test_regression_residual_spatial_autocorrelation.py", "name": "Regression residual spatial autocorrelation"},
    {"id": "08.09", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/09_run_forest_threshold_sensitivity.py", "name": "Forest-area threshold sensitivity"},
    {"id": "08.10", "group": "regression", "kind": "python", "script": "08_Regression_modeling/00_Script/10_make_figure08_final_regression_effects.py", "name": "Figure 8"},

    {"id": "09.01", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/01_compare_full_RF_and_hurdle_RF.py", "name": "Full RF versus Hurdle RF"},
    {"id": "09.02", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/02_predictor_collinearity_audit.py", "name": "RF predictor collinearity audit"},
    {"id": "09.03", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/03_compare_hurdle_RF_predictor_sets.py", "name": "Hurdle RF predictor-set comparison"},
    {"id": "09.04", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/04_compare_forest_structure_predictors.py", "name": "RF forest-structure comparison"},
    {"id": "09.05", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/05_tune_hurdle_RF_hyperparameters.py", "name": "Hurdle RF tuning"},
    {"id": "09.06", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/06_run_final_hurdle_RF_validation.py", "name": "Final Hurdle RF validation"},
    {"id": "09.07", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/07_spatial_correction_sensitivity.py", "name": "RF spatial-correction sensitivity"},
    {"id": "09.08", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/08_final_permutation_importance.py", "name": "RF permutation importance"},
    {"id": "09.09", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/09_country_effect_sensitivity.py", "name": "RF country-effect sensitivity"},
    {"id": "09.10", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/10_test_final_hurdle_RF_residual_spatial_autocorrelation.py", "name": "RF residual spatial autocorrelation"},
    {"id": "09.11", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/11_compute_oof_shap_values.py", "name": "OOF SHAP analysis"},
    {"id": "09.12", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/12_prepare_figure09_variable_importance_and_shap_candidates.py", "name": "Figure 9 data preparation"},
    {"id": "09.13", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/13_make_figure09_variable_importance_and_key_shap.py", "name": "Figure 9"},
    {"id": "09.14", "group": "rf", "kind": "python", "script": "09_RF_modeling/00_Script/14_make_figure_s6_top5_shap_profiles.py", "name": "Supplementary Figure S6"},

    {"id": "10.01", "group": "comparison", "kind": "python", "script": "10_Model_comparison/00_Script/01_build_aligned_model_oof.py", "name": "Aligned OOF datasets"},
    {"id": "10.02", "group": "comparison", "kind": "python", "script": "10_Model_comparison/00_Script/02_calculate_unified_prediction_metrics.py", "name": "Unified prediction metrics"},
    {"id": "10.03", "group": "comparison", "kind": "python", "script": "10_Model_comparison/00_Script/03_run_paired_cluster_bootstrap.py", "name": "Paired cluster bootstrap"},
    {"id": "10.04", "group": "comparison", "kind": "python", "script": "10_Model_comparison/00_Script/04_compare_residual_spatial_autocorrelation.py", "name": "Residual spatial-autocorrelation comparison"},
    {"id": "10.05", "group": "comparison", "kind": "python", "script": "10_Model_comparison/00_Script/05_calculate_country_block_annual_performance.py", "name": "Country, block, and annual performance"},
    {"id": "10.06", "group": "comparison", "kind": "python", "script": "10_Model_comparison/00_Script/06_generate_model_comparison_tables_figures.py", "name": "Model-comparison tables and figures"},
    {"id": "10.07", "group": "comparison", "kind": "python", "script": "10_Model_comparison/00_Script/07_make_figure10_unified_oof_model_comparison.py", "name": "Figure 10"},
    {"id": "10.08", "group": "comparison", "kind": "python", "script": "10_Model_comparison/00_Script/08_make_figure_s7_annual_oof_predictions.py", "name": "Supplementary Figure S7"},

    {"id": "11.01", "group": "sem", "kind": "python", "script": "11_SEM_mechanism_analysis/00_Script/01_prepare_SEM_analysis_dataset.py", "name": "SEM analysis dataset"},
    {"id": "11.02", "group": "sem", "kind": "python", "script": "11_SEM_mechanism_analysis/00_Script/02_screen_SEM_indicators_and_lock_model_form.py", "name": "SEM indicator screening"},
    {"id": "11.03", "group": "sem", "kind": "R", "script": "11_SEM_mechanism_analysis/00_Script/03_build_FAI_and_common_PCA_scores.R", "name": "SEM FAI and PCA scores"},
    {"id": "11.03a", "group": "sem", "kind": "R", "script": "11_SEM_mechanism_analysis/00_Script/03A_build_equal_contribution_FAI_sensitivity.R", "name": "Equal-contribution FAI sensitivity data"},
    {"id": "11.04", "group": "sem", "kind": "R", "script": "11_SEM_mechanism_analysis/00_Script/04_fit_three_seasonal_FAI_SEMs.R", "name": "Seasonal SEM fits"},
    {"id": "11.04a", "group": "sem", "kind": "R", "script": "11_SEM_mechanism_analysis/00_Script/04A_check_mediator_optimizer_agreement.R", "name": "SEM optimizer-agreement check"},
    {"id": "11.05", "group": "sem", "kind": "R", "script": "11_SEM_mechanism_analysis/00_Script/05_decompose_SEM_effects_and_draw_path_diagrams.R", "name": "SEM effect decomposition and path diagrams"},
    {"id": "11.06", "group": "sem", "kind": "python", "script": "11_SEM_mechanism_analysis/00_Script/06_make_figure11d_total_effects.py", "name": "Figure 11(d)"},
]

PROFILES = {
    "descriptive": {"descriptive"},
    "modeling": {"regression", "rf", "comparison", "sem"},
    "full": {"descriptive", "regression", "rf", "comparison", "sem"},
}


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def load_state() -> dict[str, Any]:
    if not STATE_FILE.exists():
        return {"completed": {}}
    try:
        return json.loads(STATE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {"completed": {}}


def save_state(state: dict[str, Any]) -> None:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    temp = STATE_FILE.with_suffix(".tmp")
    temp.write_text(json.dumps(state, indent=2, ensure_ascii=False), encoding="utf-8")
    temp.replace(STATE_FILE)


def find_rscript() -> str | None:
    configured = os.environ.get("RSCRIPT")
    if configured and Path(configured).is_file():
        return configured
    return shutil.which("Rscript")


def check_python_packages() -> list[str]:
    missing: list[str] = []
    for module, package in PYTHON_PACKAGES.items():
        if importlib.util.find_spec(module) is None:
            missing.append(package)
    return missing


def check_r_packages(rscript: str) -> list[str]:
    """Return missing R packages using the repository's canonical checker.

    Calling the checker script is more reliable on Windows than passing a long
    inline expression through ``Rscript -e``, especially when R is installed in
    a path containing spaces.
    """
    checker = ROOT / "tools" / "check_r_packages.R"
    result = subprocess.run(
        [rscript, str(checker)],
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
        cwd=ROOT,
        check=False,
    )
    if result.returncode == 0:
        return []

    combined = "\n".join(part for part in (result.stdout, result.stderr) if part)
    missing = []
    for line in combined.splitlines():
        stripped = line.strip()
        if stripped.startswith("-"):
            package = stripped[1:].strip()
            if package:
                missing.append(package)
    if missing:
        return missing

    detail = next((line.strip() for line in combined.splitlines() if line.strip()), "unknown R error")
    return [f"<unable to query R packages: {detail}>"]


def preflight(profile: str, strict: bool = True) -> bool:
    ok = True
    print(f"Repository root: {ROOT}")
    print(f"Python: {sys.executable} ({platform.python_version()})")

    required_inputs = [
        ROOT / "00_Input_data" / "Base_Table_2001_2025.csv.bz2",
        ROOT / "00_Input_data" / "Fire_Event_Table_2001_2025.csv",
        ROOT / "00_Input_data" / "Burned_Pixel_Event_Table_2001_2025.csv",
    ]
    missing_inputs = [str(p.relative_to(ROOT)) for p in required_inputs if not p.is_file()]
    if missing_inputs:
        ok = False
        print("Missing required input files:")
        for item in missing_inputs:
            print(f"  - {item}")
    else:
        print("Input data: OK")

    missing_py = check_python_packages()
    if missing_py:
        ok = False
        print("Missing Python packages:")
        print("  " + " ".join(missing_py))
        print("Install with: python -m pip install -r requirements.txt")
    else:
        print("Python packages: OK")

    selected_groups = PROFILES[profile]
    needs_r = any(step["kind"] == "R" and step["group"] in selected_groups for step in WORKFLOW)
    if needs_r:
        rscript = find_rscript()
        if not rscript:
            ok = False
            print("Rscript: NOT FOUND")
            print("Install R and ensure Rscript is available on PATH, or set RSCRIPT.")
        else:
            print(f"Rscript: {rscript}")
            missing_r = check_r_packages(rscript)
            if missing_r:
                ok = False
                print("Missing R packages:")
                for package in missing_r:
                    print(f"  - {package}")
                print("Install with: Rscript tools/install_r_packages.R")
            else:
                print("R packages: OK")

    missing_scripts = [step["script"] for step in WORKFLOW if not (ROOT / step["script"]).is_file()]
    if missing_scripts:
        ok = False
        print("Missing workflow scripts:")
        for item in missing_scripts:
            print(f"  - {item}")
    else:
        print("Workflow scripts: OK")

    if not ok and strict:
        return False
    return ok


def select_steps(profile: str, from_step: str | None, to_step: str | None) -> list[dict[str, Any]]:
    groups = PROFILES[profile]
    steps = [step for step in WORKFLOW if step["group"] in groups]
    if from_step:
        indices = [i for i, step in enumerate(steps) if step["id"] == from_step]
        if not indices:
            raise SystemExit(f"Unknown --from-step value: {from_step}")
        steps = steps[indices[0]:]
    if to_step:
        indices = [i for i, step in enumerate(steps) if step["id"] == to_step]
        if not indices:
            raise SystemExit(f"Unknown --to-step value: {to_step}")
        steps = steps[:indices[0] + 1]
    return steps


def run_step(step: dict[str, Any], rscript: str | None, dry_run: bool) -> int:
    script = ROOT / step["script"]
    if step["kind"] == "python":
        command = [sys.executable, str(script)]
    else:
        if not rscript:
            raise RuntimeError("Rscript is required for this step.")
        command = [rscript, str(script)]

    print(f"\n[{step['id']}] {step['name']}")
    print("Command:", " ".join(command))
    if dry_run:
        return 0

    LOG_DIR.mkdir(parents=True, exist_ok=True)
    safe_name = step["id"].replace(".", "_") + "_" + script.stem
    log_path = LOG_DIR / f"{safe_name}.log"
    env = os.environ.copy()
    env["WILDFIRE_CODE_ROOT"] = str(ROOT)
    env["MODEL_COMPARISON_CODE_ROOT"] = str(ROOT)
    env.setdefault("PYTHONHASHSEED", "0")
    env.setdefault("MPLBACKEND", "Agg")

    started = utc_now()
    with log_path.open("w", encoding="utf-8", newline="\n") as log:
        log.write(f"step_id: {step['id']}\n")
        log.write(f"name: {step['name']}\n")
        log.write(f"script: {step['script']}\n")
        log.write(f"started_utc: {started}\n")
        log.write(f"command: {' '.join(command)}\n\n")
        log.flush()
        process = subprocess.Popen(
            command,
            cwd=ROOT,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            bufsize=1,
        )
        assert process.stdout is not None
        for line in process.stdout:
            print(line, end="")
            log.write(line)
        return_code = process.wait()
        log.write(f"\nfinished_utc: {utc_now()}\n")
        log.write(f"return_code: {return_code}\n")
    print(f"Log: {log_path.relative_to(ROOT)}")
    return return_code


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=sorted(PROFILES), default="full")
    parser.add_argument("--from-step", help="Start at a workflow step ID, for example 08.07")
    parser.add_argument("--to-step", help="Stop after a workflow step ID")
    parser.add_argument("--resume", action="store_true", help="Skip successfully completed unchanged scripts recorded in run_logs/workflow_state.json")
    parser.add_argument("--continue-on-error", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--list", action="store_true", help="List workflow steps and exit")
    parser.add_argument("--preflight-only", action="store_true")
    parser.add_argument("--verify", action="store_true", help="Run tools/validate_reproducibility.py after the workflow")
    args = parser.parse_args()

    steps = select_steps(args.profile, args.from_step, args.to_step)
    if args.list:
        for step in steps:
            print(f"{step['id']:>6}  {step['kind']:<6}  {step['name']}\n        {step['script']}")
        return 0

    if not preflight(args.profile, strict=not args.dry_run):
        return 2
    if args.preflight_only:
        return 0

    rscript = find_rscript()
    state = load_state()
    state.setdefault("completed", {})
    input_manifest = ROOT / "00_Input_data" / "data_manifest.csv"
    input_manifest_digest = sha256(input_manifest) if input_manifest.is_file() else None
    resume_chain_valid = bool(
        args.resume
        and state.get("input_manifest_sha256") == input_manifest_digest
    )
    state["repository_root"] = str(ROOT)
    state["last_started_utc"] = utc_now()
    state["profile"] = args.profile
    state["input_manifest_sha256"] = input_manifest_digest
    save_state(state)

    failures: list[dict[str, Any]] = []
    for step in steps:
        script = ROOT / step["script"]
        digest = sha256(script)
        previous = state["completed"].get(step["id"])
        if (
            resume_chain_valid
            and previous
            and previous.get("script_sha256") == digest
            and previous.get("return_code") == 0
        ):
            print(f"\n[{step['id']}] SKIP (resume): {step['name']}")
            continue

        # Once one selected step must run, every later selected step is rerun so
        # downstream products cannot be silently reused after an upstream change.
        resume_chain_valid = False
        return_code = run_step(step, rscript, args.dry_run)
        state["completed"][step["id"]] = {
            "name": step["name"],
            "script": step["script"],
            "script_sha256": digest,
            "return_code": return_code,
            "finished_utc": utc_now(),
        }
        save_state(state)
        if return_code != 0:
            failures.append({"id": step["id"], "name": step["name"], "return_code": return_code})
            if not args.continue_on_error:
                break

    state["last_finished_utc"] = utc_now()
    state["failures"] = failures
    save_state(state)

    if failures:
        print("\nWorkflow failed:")
        for failure in failures:
            print(f"  - {failure['id']} {failure['name']} (exit {failure['return_code']})")
        return 1

    if args.verify and not args.dry_run:
        validator = ROOT / "tools" / "validate_reproducibility.py"
        result = subprocess.run([sys.executable, str(validator)], cwd=ROOT, check=False)
        if result.returncode != 0:
            return result.returncode

    print("\nWorkflow completed successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
