rm(list = ls())

library(ggplot2)
library(patchwork)
library(gridExtra)
library(ggalluvial)

# Use Times New Roman through the native Windows graphics device when available.
# This avoids Cairo/PDF CID font lookup failures on older Windows R builds while
# preserving the intended manuscript font.
plot_font_family <- "Times New Roman"
if (.Platform$OS.type == "windows") {
  try(
    do.call(
      grDevices::windowsFonts,
      setNames(
        list(grDevices::windowsFont("Times New Roman")),
        plot_font_family
      )
    ),
    silent = TRUE
  )
}


# Resolve paths relative to this script, so the code can be run from any
# working directory in RStudio or with Rscript.
get_script_dir <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  if (length(file_arg) > 0) {
    return(dirname(normalizePath(
      sub("^--file=", "", file_arg[1]),
      winslash = "/",
      mustWork = TRUE
    )))
  }
  
  frame_files <- vapply(
    sys.frames(),
    function(frame) {
      if (!is.null(frame$ofile)) as.character(frame$ofile) else NA_character_
    },
    character(1)
  )
  frame_files <- frame_files[!is.na(frame_files) & nzchar(frame_files)]
  if (length(frame_files) > 0) {
    return(dirname(normalizePath(
      tail(frame_files, 1),
      winslash = "/",
      mustWork = TRUE
    )))
  }
  
  if (
    requireNamespace("rstudioapi", quietly = TRUE) &&
    rstudioapi::isAvailable()
  ) {
    editor_path <- rstudioapi::getSourceEditorContext()$path
    if (nzchar(editor_path)) {
      return(dirname(normalizePath(
        editor_path,
        winslash = "/",
        mustWork = TRUE
      )))
    }
  }
  
  stop(
    "Cannot determine the script location. ",
    "Run the whole file with RStudio Source or Rscript."
  )
}

script_dir <- get_script_dir()
out_dir <- file.path(script_dir, "output")
if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

# Canonical event tables generated by
# 00_rebuild_canonical_fire_data_and_base_table.py.
code_root <- normalizePath(
  file.path(script_dir, ".."),
  winslash = "/",
  mustWork = TRUE
)
input_dir <- file.path(code_root, "00_Input_data")
fire_event_file <- file.path(
  input_dir,
  "Fire_Event_Table_2001_2025.csv"
)
ba_event_file <- file.path(
  input_dir,
  "Burned_Pixel_Event_Table_2001_2025.csv"
)

if (!file.exists(fire_event_file)) {
  stop("Canonical fire event table not found: ", fire_event_file)
}
if (!file.exists(ba_event_file)) {
  stop("Canonical burned-pixel event table not found: ", ba_event_file)
}

fire_events <- read.csv(
  fire_event_file,
  fileEncoding = "UTF-8-BOM",
  check.names = FALSE,
  stringsAsFactors = FALSE
)
ba_events <- read.csv(
  ba_event_file,
  fileEncoding = "UTF-8-BOM",
  check.names = FALSE,
  stringsAsFactors = FALSE
)

required_fire <- c("Fire_ID", "Country", "Year", "Month", "DOY", "FRP_MW")
required_ba <- c(
  "Burned_Pixel_ID", "Country", "Year", "Month", "DOY",
  "Burned_Area_km2"
)
if (length(setdiff(required_fire, names(fire_events))) > 0) {
  stop(
    "Canonical fire event table is missing columns: ",
    paste(setdiff(required_fire, names(fire_events)), collapse = ", ")
  )
}
if (length(setdiff(required_ba, names(ba_events))) > 0) {
  stop(
    "Canonical BA event table is missing columns: ",
    paste(setdiff(required_ba, names(ba_events)), collapse = ", ")
  )
}

normalize_country <- function(x) {
  x <- as.character(x)
  x[x == "NK"] <- "North_Korea"
  x
}
fire_events$Country <- normalize_country(fire_events$Country)
ba_events$Country <- normalize_country(ba_events$Country)

build_fc_ba_distribution <- function(group_fields) {
  fc_groups <- fire_events[, group_fields, drop = FALSE]
  fc <- aggregate(
    list(Count = rep(1, nrow(fire_events))),
    by = fc_groups,
    FUN = sum
  )
  
  ba_groups <- ba_events[, group_fields, drop = FALSE]
  ba <- aggregate(
    list(Area = ba_events$Burned_Area_km2),
    by = ba_groups,
    FUN = sum,
    na.rm = TRUE
  )
  
  complete_values <- lapply(group_fields, function(field) {
    if (field == "Year") return(2001:2025)
    if (field == "Month") return(1:12)
    if (field == "DOY") return(1:366)
    if (field == "Country") return(c("China", "North_Korea", "Russia"))
    sort(unique(c(fire_events[[field]], ba_events[[field]])))
  })
  names(complete_values) <- group_fields
  complete_grid <- do.call(
    expand.grid,
    c(
      complete_values,
      list(KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
    )
  )
  
  output <- merge(complete_grid, fc, by = group_fields, all.x = TRUE)
  output <- merge(output, ba, by = group_fields, all.x = TRUE)
  output$Count[is.na(output$Count)] <- 0
  output$Area[is.na(output$Area)] <- 0
  output
}

# ============================================================
# 1. Functions for Mann-Kendall-equivalent Kendall trend test
#    and Sen's slope
# ============================================================

sen_fit <- function(x, y) {
  ok <- complete.cases(x, y)
  x <- x[ok]
  y <- y[ok]
  
  if (length(x) < 2) {
    stop("At least two complete observations are required.")
  }
  
  pair_index <- combn(seq_along(x), 2)
  dx <- x[pair_index[2, ]] - x[pair_index[1, ]]
  dy <- y[pair_index[2, ]] - y[pair_index[1, ]]
  
  valid_pairs <- dx != 0
  slopes <- dy[valid_pairs] / dx[valid_pairs]
  
  slope <- median(slopes, na.rm = TRUE)
  intercept <- median(y - slope * x, na.rm = TRUE)
  
  list(
    slope = slope,
    intercept = intercept
  )
}

trend_test <- function(data, response, period_name) {
  x <- data$Year
  y <- data[[response]]
  ok <- complete.cases(x, y)
  x <- x[ok]
  y <- y[ok]
  
  mk <- cor.test(
    x,
    y,
    method = "kendall",
    exact = FALSE
  )
  
  sen <- sen_fit(x, y)
  
  data.frame(
    Period = period_name,
    Response = response,
    N = length(y),
    Kendall_tau = unname(mk$estimate),
    P_value = mk$p.value,
    Sen_slope = sen$slope,
    stringsAsFactors = FALSE
  )
}


fmt_num <- function(x, digits = 3) {
  formatC(x, format = "f", digits = digits)
}

fmt_p <- function(p) {
  ifelse(p < 0.001, "< 0.001", paste0("= ", formatC(p, format = "f", digits = 3)))
}

# ============================================================
# 2. Annual data and Fig. 3a
# ============================================================

mydataYear_raw <- build_fc_ba_distribution(c("Year", "Country"))
mydataYear_raw$Year <- as.integer(mydataYear_raw$Year)

mydataYear_raw$Country <- factor(
  mydataYear_raw$Country,
  levels = c("Russia", "North_Korea", "China")
)

# Regional annual totals in reported units
annual_total <- aggregate(
  cbind(Area, Count) ~ Year,
  data = mydataYear_raw,
  FUN = sum,
  na.rm = TRUE
)
annual_total <- annual_total[order(annual_total$Year), ]

# Full-period trend tests
trend_full <- rbind(
  trend_test(annual_total, "Count", "2001-2025"),
  trend_test(annual_total, "Area", "2001-2025")
)

# Sensitivity analysis excluding both early peak years
annual_without_peaks <- subset(
  annual_total,
  !(Year %in% c(2003, 2008))
)

trend_without_peaks <- rbind(
  trend_test(
    annual_without_peaks,
    "Count",
    "2001-2025 excluding 2003 and 2008"
  ),
  trend_test(
    annual_without_peaks,
    "Area",
    "2001-2025 excluding 2003 and 2008"
  )
)

annual_trend_results <- rbind(
  trend_full,
  trend_without_peaks
)

print(annual_trend_results)

write.csv(
  annual_trend_results,
  file.path(out_dir, "Annual_FC_BA_trend_results.csv"),
  row.names = FALSE,
  fileEncoding = "UTF-8"
)

# Convert country-level data to the plotting units used in Figure 3
mydataYear <- mydataYear_raw
mydataYear$Area <- mydataYear$Area / 1000
mydataYear$Count <- mydataYear$Count / 1000

# Prepare regional totals on the same plotting scales as Fig. 3a
annual_total$Area_plot <- annual_total$Area / 1000
annual_total$Count_plot <- annual_total$Count / 1000 * 0.5

# Sen trend line for total Burned Area
sen_area_plot <- sen_fit(
  annual_total$Year,
  annual_total$Area_plot
)
annual_total$Area_trend <-
  sen_area_plot$intercept +
  sen_area_plot$slope * annual_total$Year

# Sen trend line for total Fire Count
sen_count_plot <- sen_fit(
  annual_total$Year,
  annual_total$Count_plot
)
annual_total$Count_trend <-
  sen_count_plot$intercept +
  sen_count_plot$slope * annual_total$Year

# Prepare two-line legend labels for the regional Sen trend lines.
# The second line is indented so that "Sen's slope" starts below tau.
fc_full <- subset(
  annual_trend_results,
  Period == "2001-2025" & Response == "Count"
)
ba_full <- subset(
  annual_trend_results,
  Period == "2001-2025" & Response == "Area"
)

format_legend_number <- function(x, digits) {
  value <- formatC(x, format = "f", digits = digits)
  sub("^-", "\u2212", value)
}

ba_tau_text <- format_legend_number(ba_full$Kendall_tau[1], 3)
ba_p_text <- format_legend_number(ba_full$P_value[1], 3)
ba_slope_text <- format_legend_number(ba_full$Sen_slope[1], 2)

fc_tau_text <- format_legend_number(fc_full$Kendall_tau[1], 3)
fc_p_text <- format_legend_number(fc_full$P_value[1], 3)
fc_slope_text <- format_legend_number(fc_full$Sen_slope[1], 2)

trend_legend_labels <- c(
  paste0(
    "BA: \u03c4 = ", ba_tau_text, ", p = ", ba_p_text, "\n",
    "Sen's slope = ", ba_slope_text, " km\u00b2 yr\u207b\u00b9"
  ),
  paste0(
    "FC: \u03c4 = ", fc_tau_text, ", p = ", fc_p_text, "\n",
    "Sen's slope = ", fc_slope_text, " fires yr\u207b\u00b9"
  )
)

trend_plot_data <- rbind(
  data.frame(
    Year = annual_total$Year,
    Trend_value = annual_total$Area_trend,
    Trend = "Burned Area"
  ),
  data.frame(
    Year = annual_total$Year,
    Trend_value = annual_total$Count_trend,
    Trend = "Fire Count"
  )
)

trend_plot_data$Trend <- factor(
  trend_plot_data$Trend,
  levels = c("Burned Area", "Fire Count")
)

p1 <- ggplot(
  mydataYear,
  aes(x = Year, y = Area, alluvium = Country)
) +
  geom_alluvium(
    aes(fill = Country, colour = Country),
    alpha = 0.35,
    width = 0.5,
    size = 0.2
  ) +
  geom_bar(
    stat = "identity",
    aes(fill = Country),
    width = 0.5
  ) +
  geom_line(
    aes(y = Count * 0.5, color = Country),
    size = 0.5
  ) +
  geom_point(
    aes(y = Count * 0.5, color = Country),
    size = 1
  ) +
  
  # Regional Sen trend lines. Line type is explained directly in the legend.
  geom_line(
    data = trend_plot_data,
    aes(x = Year, y = Trend_value, linetype = Trend),
    inherit.aes = FALSE,
    colour = "grey35",
    alpha = 0.72,
    linewidth = 0.52
  ) +
  
  scale_x_continuous(
    breaks = seq(2001, 2025, 1),
    expand = c(0.01, 0)
  ) +
  scale_y_continuous(
    breaks = seq(0, 6, 1),
    expand = c(0.002, 0),
    sec.axis = sec_axis(
      ~ . / 0.5,
      name = expression("Fire Count" ~ "(1*10"^3*")"),
      breaks = seq(0, 12, 3)
    )
  ) +
  labs(
    x = "Year",
    y = expression("Burned Area (1*10"^3*" km"^2*")"),
    title = "(a)"
  ) +
  scale_fill_manual(
    values = c(
      "China" = "#FF6347",
      "North_Korea" = "#FFA500",
      "Russia" = "#4682B4"
    )
  ) +
  scale_color_manual(
    values = c(
      "China" = "#DC143C",
      "North_Korea" = "#FFDF00",
      "Russia" = "#00008B"
    )
  ) +
  scale_linetype_manual(
    name = NULL,
    breaks = c("Burned Area", "Fire Count"),
    values = c(
      "Burned Area" = "longdash",
      "Fire Count" = "dotted"
    ),
    labels = trend_legend_labels
  ) +
  guides(
    fill = "none",
    colour = "none",
    linetype = guide_legend(
      override.aes = list(
        colour = "grey25",
        alpha = 1,
        linewidth = 0.75
      )
    )
  ) +
  theme(
    legend.position = c(0.985, 0.985),
    legend.justification = c(1, 1),
    legend.direction = "vertical",
    legend.background = element_rect(
      fill = scales::alpha("white", 0.82),
      colour = "grey70",
      linewidth = 0.25
    ),
    legend.key = element_blank(),
    legend.key.width = grid::unit(1.35, "cm"),
    legend.key.height = grid::unit(1.25, "cm"),
    legend.text = element_text(
      family = plot_font_family,
      size = 14,
      lineheight = 0.95
    ),
    panel.grid.minor = element_line(size = 0.3),
    panel.grid.major = element_line(colour = NA),
    axis.title = element_text(
      family = plot_font_family,
      size = 18
    ),
    axis.text = element_text(
      family = plot_font_family,
      size = 14
    ),
    axis.text.x = element_text(
      angle = -30,
      hjust = 0
    ),
    plot.title = element_text(
      family = plot_font_family,
      size = 20
    )
  )


# ============================================================
# 3. Monthly data and Fig. 3b
# ============================================================

mydataMonth <- build_fc_ba_distribution(c("Month", "Country"))
mydataMonth$Month <- as.integer(mydataMonth$Month)
mydataMonth$Country <- factor(
  mydataMonth$Country,
  levels = c("Russia", "North_Korea", "China")
)
mydataMonth$Area <- mydataMonth$Area / 1000
mydataMonth$Count <- mydataMonth$Count / 1000

p2 <- ggplot(
  mydataMonth,
  aes(x = Month, y = Area, alluvium = Country)
) +
  geom_alluvium(
    aes(fill = Country, colour = Country),
    alpha = 0.35,
    width = 0.5,
    size = 0.2
  ) +
  geom_bar(
    stat = "identity",
    aes(fill = Country),
    width = 0.5
  ) +
  geom_line(
    aes(y = Count * 0.5, color = Country),
    size = 0.5
  ) +
  geom_point(
    aes(y = Count * 0.5, color = Country),
    size = 1
  ) +
  scale_x_continuous(
    breaks = seq(0, 12, 1),
    expand = c(0.01, 0)
  ) +
  scale_y_continuous(
    breaks = seq(0, 20, 4),
    expand = c(0.002, 0),
    sec.axis = sec_axis(
      ~ . / 0.5,
      name = expression("Fire Count" ~ "(1*10"^3*")"),
      breaks = seq(0, 40, 10)
    )
  ) +
  labs(
    x = "Month",
    y = expression("Burned Area (1*10"^3*" km"^2*")"),
    title = "(b)"
  ) +
  scale_fill_manual(
    values = c(
      "China" = "#FF6347",
      "North_Korea" = "#FFA500",
      "Russia" = "#4682B4"
    )
  ) +
  scale_color_manual(
    values = c(
      "China" = "#DC143C",
      "North_Korea" = "#FFDF00",
      "Russia" = "#00008B"
    )
  ) +
  theme(
    legend.position = "none",
    panel.grid.minor = element_line(size = 0.3),
    panel.grid.major = element_line(colour = NA),
    axis.title = element_text(
      family = plot_font_family,
      size = 18
    ),
    axis.text = element_text(
      family = plot_font_family,
      size = 14
    ),
    plot.title = element_text(
      family = plot_font_family,
      size = 20
    )
  )


# ============================================================
# 4. Daily data and Fig. 3c
# ============================================================

mydataDay <- build_fc_ba_distribution(c("DOY", "Country"))
names(mydataDay)[names(mydataDay) == "DOY"] <- "Day_number"
mydataDay$Day_number <- as.integer(mydataDay$Day_number)
mydataDay$Country <- factor(
  mydataDay$Country,
  levels = c("Russia", "North_Korea", "China")
)

p3 <- ggplot(
  mydataDay,
  aes(x = Day_number, y = Area, fill = Country)
) +
  annotate(
    "rect",
    xmin = 43.5,
    xmax = 160.5,
    ymin = -Inf,
    ymax = Inf,
    fill = "#B3DE69",
    alpha = 0.3
  ) +
  annotate(
    "rect",
    xmin = 160.5,
    xmax = 218.5,
    ymin = -Inf,
    ymax = Inf,
    fill = "#FB8072",
    alpha = 0.3
  ) +
  annotate(
    "rect",
    xmin = 268.5,
    xmax = 331.5,
    ymin = -Inf,
    ymax = Inf,
    fill = "#FFED6F",
    alpha = 0.3
  ) +
  geom_bar(
    stat = "identity",
    width = 1
  ) +
  geom_line(
    aes(y = Count * 0.5, color = Country),
    size = 0.5
  ) +
  scale_x_continuous(
    breaks = seq(0, 366, 30),
    expand = c(0.002, 0)
  ) +
  scale_y_continuous(
    breaks = seq(0, 2000, 400),
    expand = c(0.002, 0),
    sec.axis = sec_axis(
      ~ . / 0.5,
      name = "Fire Count",
      breaks = seq(0, 3000, 800)
    )
  ) +
  labs(
    x = "Day of year",
    y = expression("Burned Area (km"^2*")"),
    title = "(c)"
  ) +
  scale_fill_manual(
    values = c(
      "China" = "#FF6347",
      "North_Korea" = "#FFA500",
      "Russia" = "#4682B4"
    ),
    breaks = c("China", "North_Korea", "Russia"),
    labels = c("China", "North Korea", "Russia")
  ) +
  scale_color_manual(
    values = c(
      "China" = "#DC143C",
      "North_Korea" = "#FFDF00",
      "Russia" = "#00008B"
    ),
    breaks = c("China", "North_Korea", "Russia"),
    labels = c("China", "North Korea", "Russia")
  ) +
  labs(
    fill = "Burned Area by Countries",
    color = "Fire Count by Countries"
  ) +
  theme(
    panel.grid.major = element_line(size = 0.3),
    panel.grid.minor = element_line(colour = NA),
    legend.title = element_text(
      family = plot_font_family,
      face = "bold",
      size = 18
    ),
    legend.text = element_text(
      family = plot_font_family,
      size = 16
    ),
    axis.title = element_text(
      family = plot_font_family,
      size = 18
    ),
    axis.text = element_text(
      family = plot_font_family,
      size = 14
    ),
    plot.title = element_text(
      family = plot_font_family,
      size = 20
    )
  ) +
  annotate(
    "text",
    x = 44,
    y = 1400,
    label = "Spring\nFeb 13-Jun 9",
    vjust = 1,
    hjust = 0,
    color = "#666666",
    size = 5,
    family = plot_font_family
  ) +
  annotate(
    "text",
    x = 161,
    y = 1400,
    label = "Summer\nJun 10-Aug 6",
    vjust = 1,
    hjust = 0,
    color = "#666666",
    size = 5,
    family = plot_font_family
  ) +
  annotate(
    "text",
    x = 269,
    y = 1400,
    label = "Autumn\nSep 26-Nov 27",
    vjust = 1,
    hjust = 0,
    color = "#666666",
    size = 5,
    family = plot_font_family
  )


# ============================================================
# 5. Extract legend and export the combined figure
# ============================================================

layout <- "
AAAAAABBB
CCCCCCCDD
"

tiff_args <- list(
  filename = file.path(
    out_dir,
    "Figure_3_Temporal_patterns_with_Sen_trends.tif"
  ),
  width = 15,
  height = 8,
  units = "in",
  res = 300,
  compression = "lzw"
)

if (.Platform$OS.type == "windows") {
  tiff_args$type <- "windows"
} else if (capabilities("cairo")) {
  tiff_args$type <- "cairo"
}

# Open the final output device before constructing or measuring grobs.
# Under Rscript on Windows, evaluating a ggplot before a device is open can
# silently create Rplots.pdf; that PDF device cannot resolve the registered
# Windows Times New Roman font and causes a PDF CID font error.
do.call(grDevices::tiff, tiff_args)

p3_grob <- ggplotGrob(p3)
legend_index <- which(
  sapply(
    p3_grob$layout$name,
    function(x) x == "guide-box-right"
  )
)

if (length(legend_index) == 0) {
  legend_index <- which(
    grepl("guide-box", p3_grob$layout$name)
  )[1]
}

legend_grob <- p3_grob$grobs[[legend_index]]
p4 <- gridExtra::arrangeGrob(legend_grob, ncol = 1)

print(
  p1 + p2 + p3 + p4 +
    plot_layout(design = layout) &
    guides(fill = FALSE, color = FALSE)
)

dev.off()

# Optional high-resolution PNG output
# ggsave(
#   file.path(out_dir, "Figure_3_Temporal_patterns_with_Sen_trends.png"),
#   plot = p1 + p2 + p3 + p4 +
#     plot_layout(design = layout) &
#     guides(fill = FALSE, color = FALSE),
#   width = 15,
#   height = 8,
#   dpi = 600
# )
