# -*- coding: utf-8 -*-
"""
Estimate country-level Fire Count and Burned Area trends by fire season.

Input
-----
Canonical Base_Table_2001_2025.csv.bz2 generated by:
    00_rebuild_canonical_fire_data_and_base_table.py

The script aggregates the base table directly; no intermediate input CSV is required.

Output
------
output/country_season_fc_ba_trend_results_2001_2025.csv

The script calculates country shares, Kendall's tau, Sen's slope, and
Benjamini-Hochberg false-discovery-rate adjusted p-values.
"""

from pathlib import Path
import math
import statistics
import pandas as pd
from scipy.stats import kendalltau

SCRIPT_DIR = Path(__file__).resolve().parent
CODE_ROOT = SCRIPT_DIR.parent
INPUT_DIR = CODE_ROOT / "00_Input_data"
INPUT = INPUT_DIR / "Base_Table_2001_2025.csv.bz2"
OUTPUT_DIR = SCRIPT_DIR / "output"
OUTPUT_DIR.mkdir(exist_ok=True)

COUNTRY_ORDER = ["China", "North_Korea", "Russia"]
SEASON_ORDER = ["Spring", "Summer", "Autumn"]


def sen_slope(years, values):
    slopes = []
    for i in range(len(years) - 1):
        for j in range(i + 1, len(years)):
            dx = years[j] - years[i]
            if dx != 0:
                slopes.append((values[j] - values[i]) / dx)
    return float(statistics.median(slopes)) if slopes else float("nan")


def trend_stats(years, values):
    tau, p_value = kendalltau(years, values, nan_policy="omit")
    return {
        "tau": float(tau) if tau is not None else float("nan"),
        "p": float(p_value) if p_value is not None else float("nan"),
        "sen": sen_slope(years, values),
    }


def bh_adjust(values):
    p_values = list(values)
    valid = [
        (index, value)
        for index, value in enumerate(p_values)
        if not math.isnan(value)
    ]
    output = [float("nan")] * len(p_values)

    if not valid:
        return output

    ordered = sorted(valid, key=lambda item: item[1])
    previous = 1.0
    m = len(ordered)

    for reverse_index, (original_index, value) in enumerate(
        reversed(ordered), start=1
    ):
        rank = m - reverse_index + 1
        adjusted = min(previous, value * m / rank)
        output[original_index] = min(adjusted, 1.0)
        previous = adjusted

    return output


def trend_label(tau, p_value):
    if math.isnan(tau) or math.isnan(p_value):
        return "Not available"
    if p_value >= 0.05:
        return "No significant trend"
    return "Decreasing" if tau < 0 else "Increasing"


def main():
    if not INPUT.exists():
        raise FileNotFoundError(f"Canonical base table not found:\n{INPUT}")

    base = pd.read_csv(
        INPUT,
        usecols=["Country", "Year", "Season", "Fire_Count", "Burned_Pixel_Count"],
        encoding="utf-8-sig",
        low_memory=False,
    )
    base["Country"] = base["Country"].replace({
        "NK": "North_Korea",
        "North Korea": "North_Korea",
    })
    base["Year"] = pd.to_numeric(base["Year"], errors="raise").astype(int)
    base["Season"] = pd.to_numeric(base["Season"], errors="raise").astype(int)
    base["Fire_Count"] = pd.to_numeric(base["Fire_Count"], errors="raise")
    base["Burned_Pixel_Count"] = pd.to_numeric(
        base["Burned_Pixel_Count"], errors="raise"
    )

    data = (
        base.groupby(["Year", "Season", "Country"], as_index=False)
        .agg(
            Fire_Count=("Fire_Count", "sum"),
            Burned_Pixel_Count=("Burned_Pixel_Count", "sum"),
        )
    )
    data["Burned_Area_km2"] = data["Burned_Pixel_Count"] * 0.25
    data["Season"] = data["Season"].map({
        1: "Spring", 2: "Summer", 3: "Autumn"
    })
    data = data[["Year", "Season", "Country", "Fire_Count", "Burned_Area_km2"]]
    data.to_csv(
        OUTPUT_DIR / "country_season_input_from_base_table.csv",
        index=False, encoding="utf-8-sig"
    )

    if data.duplicated(["Year", "Season", "Country"]).any():
        raise ValueError("Duplicate Year-Season-Country rows after aggregation.")
    if len(data) != 225:
        raise ValueError(f"Expected 225 aggregated rows; found {len(data)}.")
    if sorted(data["Year"].unique().tolist()) != list(range(2001, 2026)):
        raise ValueError("Input must contain exactly 2001-2025.")
    if set(data["Country"]) != set(COUNTRY_ORDER):
        raise ValueError(f"Unexpected country labels: {sorted(data['Country'].unique())}")
    if set(data["Season"]) != set(SEASON_ORDER):
        raise ValueError("Unexpected season labels after aggregation.")
    if (data[["Fire_Count", "Burned_Area_km2"]] < 0).any().any():
        raise ValueError("Negative FC/BA values found in canonical base table.")

    rows = []

    for period in SEASON_ORDER:
        period_data = data[data["Season"] == period]

        for country in COUNTRY_ORDER:
            group = (
                period_data[period_data["Country"] == country]
                .sort_values("Year")
            )

            fc_stats = trend_stats(
                group["Year"].tolist(),
                group["Fire_Count"].tolist(),
            )
            ba_stats = trend_stats(
                group["Year"].tolist(),
                group["Burned_Area_km2"].tolist(),
            )

            fc_total = float(group["Fire_Count"].sum())
            ba_total = float(group["Burned_Area_km2"].sum())

            rows.append({
                "Period": period,
                "Country": country,
                "FC_total": int(round(fc_total)),
                "FC_share_pct": (
                    fc_total / float(period_data["Fire_Count"].sum()) * 100
                ),
                "FC_tau": fc_stats["tau"],
                "FC_p_raw": fc_stats["p"],
                "FC_Sen_slope_per_year": fc_stats["sen"],
                "BA_total_km2": ba_total,
                "BA_share_pct": (
                    ba_total
                    / float(period_data["Burned_Area_km2"].sum())
                    * 100
                ),
                "BA_tau": ba_stats["tau"],
                "BA_p_raw": ba_stats["p"],
                "BA_Sen_slope_km2_per_year": ba_stats["sen"],
            })

    result = pd.DataFrame(rows)
    result["FC_p_FDR"] = bh_adjust(result["FC_p_raw"].tolist())
    result["BA_p_FDR"] = bh_adjust(result["BA_p_raw"].tolist())
    result["FC_trend"] = [
        trend_label(tau, p_value)
        for tau, p_value in zip(result["FC_tau"], result["FC_p_FDR"])
    ]
    result["BA_trend"] = [
        trend_label(tau, p_value)
        for tau, p_value in zip(result["BA_tau"], result["BA_p_FDR"])
    ]

    output = (
        OUTPUT_DIR
        / "country_season_fc_ba_trend_results_2001_2025.csv"
    )
    result.to_csv(output, index=False, encoding="utf-8-sig")
    print(output)


if __name__ == "__main__":
    main()
