# -*- coding: utf-8 -*-
"""
Estimate annual and seasonal trends in Fire Radiative Power (FRP), 2001-2025.

The script reads the canonical single-fire event table generated by:
    00_rebuild_canonical_fire_data_and_base_table.py

It calculates annual and official-season FRP statistics directly from individual
fire detections, preserving exact mean, median and 95th-percentile values.
"""

from pathlib import Path
import numpy as np
import pandas as pd
from scipy.stats import kendalltau

SCRIPT_DIR = Path(__file__).resolve().parent
CODE_ROOT = SCRIPT_DIR.parent
INPUT_DIR = CODE_ROOT / "00_Input_data"
INPUT = INPUT_DIR / "Fire_Event_Table_2001_2025.csv"
OUTPUT_DIR = SCRIPT_DIR / "output"
OUTPUT_DIR.mkdir(exist_ok=True)

MIN_TREND_YEARS = 10
YEARS = list(range(2001, 2026))
SEASON_LABELS = {1: "Spring", 2: "Summer", 3: "Autumn"}


def sen_slope(years, values):
    years = np.asarray(years, dtype=float)
    values = np.asarray(values, dtype=float)
    mask = np.isfinite(years) & np.isfinite(values)
    years = years[mask]
    values = values[mask]
    if len(values) < 2:
        return np.nan
    slopes = []
    for i in range(len(values) - 1):
        dx = years[i + 1:] - years[i]
        dy = values[i + 1:] - values[i]
        valid = dx != 0
        slopes.extend((dy[valid] / dx[valid]).tolist())
    return float(np.median(slopes)) if slopes else np.nan


def trend_test(years, values):
    years = np.asarray(years, dtype=float)
    values = np.asarray(values, dtype=float)
    mask = np.isfinite(years) & np.isfinite(values)
    x = years[mask]
    y = values[mask]
    result = {
        "N_years": int(len(y)), "Tau": np.nan, "P_value": np.nan,
        "Sen_slope": np.nan, "Trend": "Not estimated",
    }
    if len(y) < MIN_TREND_YEARS or len(np.unique(y)) < 2:
        return result
    tau, p_value = kendalltau(x, y, nan_policy="omit")
    slope = sen_slope(x, y)
    result.update({
        "Tau": float(tau) if np.isfinite(tau) else np.nan,
        "P_value": float(p_value) if np.isfinite(p_value) else np.nan,
        "Sen_slope": float(slope) if np.isfinite(slope) else np.nan,
    })
    if np.isfinite(p_value) and p_value < 0.05:
        result["Trend"] = "Significant increase" if tau > 0 else "Significant decrease"
    else:
        result["Trend"] = "Not significant"
    return result


def benjamini_hochberg(p_values):
    p = np.asarray(p_values, dtype=float)
    adjusted = np.full(len(p), np.nan, dtype=float)
    valid_idx = np.where(np.isfinite(p))[0]
    if len(valid_idx) == 0:
        return adjusted
    valid_p = p[valid_idx]
    order = np.argsort(valid_p)
    ranked = valid_p[order]
    m = len(ranked)
    q = ranked * m / np.arange(1, m + 1)
    q = np.minimum.accumulate(q[::-1])[::-1]
    q = np.clip(q, 0, 1)
    temp = np.empty(m, dtype=float)
    temp[order] = q
    adjusted[valid_idx] = temp
    return adjusted


def summarize_group(group: pd.DataFrame) -> dict:
    values = group["FRP_MW"].to_numpy(dtype=float)
    return {
        "Fire_Count": int(len(values)),
        "Total_FRP_MW": float(np.sum(values)),
        "Mean_FRP_MW": float(np.mean(values)) if len(values) else np.nan,
        "Median_FRP_MW": float(np.median(values)) if len(values) else np.nan,
        "P95_FRP_MW": float(np.quantile(values, 0.95)) if len(values) else np.nan,
    }


def build_series(events: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for year in YEARS:
        annual = events[events["Year"] == year]
        rows.append({"Country": "All", "Season": "Annual", "Year": year, **summarize_group(annual)})
        for code, label in SEASON_LABELS.items():
            subset = annual[annual["Season"] == code]
            rows.append({"Country": "All", "Season": label, "Year": year, **summarize_group(subset)})
    return pd.DataFrame(rows)


def main():
    if not INPUT.exists():
        raise FileNotFoundError(f"Canonical fire event table not found:\n{INPUT}")
    events = pd.read_csv(INPUT, encoding="utf-8-sig", low_memory=False)
    required = {"Fire_ID", "Year", "Season", "FRP_MW"}
    missing = required.difference(events.columns)
    if missing:
        raise ValueError(f"Missing columns: {sorted(missing)}")
    events["Year"] = pd.to_numeric(events["Year"], errors="raise").astype(int)
    events["Season"] = pd.to_numeric(events["Season"], errors="raise").astype(int)
    events["FRP_MW"] = pd.to_numeric(events["FRP_MW"], errors="raise")
    if events["Fire_ID"].duplicated().any():
        raise ValueError("Duplicate Fire_ID values in canonical fire event table.")
    if events["FRP_MW"].isna().any() or (events["FRP_MW"] < 0).any():
        raise ValueError("Missing or negative FRP values found.")

    series = build_series(events)
    series.to_csv(
        OUTPUT_DIR / "annual_seasonal_frp_series_2001_2025.csv",
        index=False, encoding="utf-8-sig", float_format="%.6f",
    )

    metric_units = {
        "Fire_Count": "detections yr-1",
        "Total_FRP_MW": "MW yr-1",
        "Mean_FRP_MW": "MW",
        "Median_FRP_MW": "MW",
        "P95_FRP_MW": "MW",
    }
    rows = []
    for (country, season), group in series.groupby(["Country", "Season"], sort=False):
        group = group.sort_values("Year")
        for metric, slope_unit in metric_units.items():
            result = trend_test(group["Year"].to_numpy(), group[metric].to_numpy())
            rows.append({
                "Country": country, "Season": season, "Metric": metric,
                "N_years": result["N_years"], "Tau": result["Tau"],
                "P_value": result["P_value"], "Sen_slope": result["Sen_slope"],
                "Slope_unit": slope_unit, "Trend_raw_p": result["Trend"],
            })

    trend = pd.DataFrame(rows)
    trend["P_FDR"] = np.nan
    for _, indices in trend.groupby("Metric").groups.items():
        indices = list(indices)
        trend.loc[indices, "P_FDR"] = benjamini_hochberg(
            trend.loc[indices, "P_value"].to_numpy(dtype=float)
        )

    def classify(row):
        if not np.isfinite(row["P_FDR"]):
            return "Not estimated"
        if row["P_FDR"] < 0.05:
            if row["Tau"] > 0:
                return "Significant increase"
            if row["Tau"] < 0:
                return "Significant decrease"
        return "Not significant"

    trend["Trend_FDR"] = trend.apply(classify, axis=1)
    trend = trend[[
        "Country", "Season", "Metric", "N_years", "Tau", "P_value",
        "P_FDR", "Sen_slope", "Slope_unit", "Trend_raw_p", "Trend_FDR",
    ]]
    output = OUTPUT_DIR / "frp_trend_results_2001_2025.csv"
    trend.to_csv(output, index=False, encoding="utf-8-sig", float_format="%.6f")
    print(output)


if __name__ == "__main__":
    main()
