# -*- coding: utf-8 -*-
"""
Model Comparison Step 03
Paired stratified GRID_UID-cluster bootstrap for three locked OOF models.

This script reads the aligned Temporal and Spatial OOF predictions produced by
Model Comparison Step 01 and the locked point metrics produced by Step 02.

It does not fit, tune, select, or predict any model.
"""

from __future__ import annotations

import ast
import hashlib
import json
import math
import platform
import shutil
import sys
import traceback
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Mapping, Sequence, Tuple

import numpy as np
import pandas as pd
import scipy
import sklearn


# =============================================================================
# Paths and locked settings
# =============================================================================

SCRIPT_DIR = Path(__file__).resolve().parent
MODEL_COMPARISON_ROOT = SCRIPT_DIR.parent

STEP01_ROOT = MODEL_COMPARISON_ROOT / "01_Aligned_Model_OOF"
STEP02_ROOT = MODEL_COMPARISON_ROOT / "02_Unified_Prediction_Metrics"

ALIGNED_FILES = {
    "Temporal": STEP01_ROOT / "05_Aligned_Temporal_OOF.csv.gz",
    "Spatial": STEP01_ROOT / "06_Aligned_Spatial_OOF.csv.gz",
}

STEP01_METHOD_FILE = STEP01_ROOT / "00_Method_Definition.json"
STEP01_MANIFEST_FILE = STEP01_ROOT / "07_Aligned_OOF_Manifest.csv"

STEP02_METHOD_FILE = STEP02_ROOT / "00_Method_Definition.json"
STEP02_OVERALL_FILE = (
    STEP02_ROOT / "02_Overall_Unified_Prediction_Metrics.csv"
)
STEP02_FOLD_FILE = (
    STEP02_ROOT / "03_Fold_Level_Unified_Prediction_Metrics.csv"
)
STEP02_MANIFEST_FILE = STEP02_ROOT / "09_Output_Manifest.csv"

OUTPUT_ROOT = MODEL_COMPARISON_ROOT / "03_Paired_Cluster_Bootstrap"
LOG_FILE = OUTPUT_ROOT / "paired_cluster_bootstrap.log"

CODE_VERSION = (
    "2026-06-30_MODEL_COMPARISON_PAIRED_GRID_CLUSTER_BOOTSTRAP_V1"
)
EXPECTED_STEP01_VERSION = "2026-06-30_MODEL_COMPARISON_ALIGNED_OOF_V1"
EXPECTED_STEP02_VERSION = (
    "2026-06-30_MODEL_COMPARISON_UNIFIED_METRICS_"
    "V1A_ZERO_POSITIVE_FOLD_COMPATIBILITY"
)

# Compressed CSV byte hashes are verified against the manifest generated by
# Step 01 in the same run. A fixed hash of a .csv.gz file is intentionally not
# used because gzip headers may contain run-specific metadata even when the
# decompressed table is identical. Structural and semantic checks below still
# lock row counts, keys, grids, years, responses, and paired observations.

BOOTSTRAP_REPLICATES = 2_000
BOOTSTRAP_RANDOM_SEED = 20_260_630
CI_LEVEL = 0.95

EXPECTED_ROWS_PER_SCHEME = 742_374
EXPECTED_ROWS_PER_COMBINATION = 123_729
EXPECTED_GRID_COUNT = 4_982
EXPECTED_YEARS = 25

SEASONS = {
    1: "Spring",
    2: "Summer",
    3: "Autumn",
}

RESPONSES = [
    "Fire_Count",
    "Burned_Pixel_Count",
]

MODELS = [
    "Baseline_NB1",
    "Final_Regression",
    "Final_Hurdle_RF",
]

MODEL_PAIRS = [
    (
        "Final_Regression_vs_Baseline_NB1",
        "Final_Regression",
        "Baseline_NB1",
    ),
    (
        "Final_Hurdle_RF_vs_Baseline_NB1",
        "Final_Hurdle_RF",
        "Baseline_NB1",
    ),
    (
        "Final_Hurdle_RF_vs_Final_Regression",
        "Final_Hurdle_RF",
        "Final_Regression",
    ),
]

# These primary paired-bootstrap metrics can be calculated exactly from
# GRID_UID-level sufficient statistics. All are lower-is-better.
BOOTSTRAP_METRICS = [
    "Rate_RMSE",
    "Rate_MAE",
    "Count_RMSE",
    "Count_MAE",
    "Occurrence_Brier_Score",
    "Positive_Conditional_Rate_RMSE",
    "Positive_Conditional_Rate_MAE",
    "Positive_Conditional_Count_RMSE",
    "Positive_Conditional_Count_MAE",
    "Rate_Absolute_Mean_Bias",
    "Count_Absolute_Mean_Bias",
    "Occurrence_Absolute_Mean_Bias",
]

NONADDITIVE_DESCRIPTIVE_METRICS = {
    "Rate_R2": "Higher",
    "Rate_Spearman": "Higher",
    "Count_R2": "Higher",
    "Count_Spearman": "Higher",
    "Occurrence_PR_AUC": "Higher",
    "Occurrence_ROC_AUC": "Higher",
    "Positive_Conditional_Rate_Spearman": "Higher",
    "Occurrence_Expected_Calibration_Error": "Lower",
    "Rate_Binned_Calibration_MAE": "Lower",
}

HASH_CHUNK_SIZE = 1024 * 1024
NUMERIC_ATOL = 2e-11
NUMERIC_RTOL = 2e-9


# =============================================================================
# Logging and basic helpers
# =============================================================================

def log(message: str) -> None:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{timestamp}] {message}"
    print(line, flush=True)

    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    with LOG_FILE.open("a", encoding="utf-8") as file:
        file.write(line + "\n")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()

    with path.open("rb") as file:
        while True:
            chunk = file.read(HASH_CHUNK_SIZE)

            if not chunk:
                break

            digest.update(chunk)

    return digest.hexdigest()


def sha256_array(array: np.ndarray) -> str:
    contiguous = np.ascontiguousarray(array)
    return hashlib.sha256(contiguous.tobytes()).hexdigest()


def read_json(path: Path) -> Dict[str, object]:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def write_json(path: Path, value: object) -> None:
    with path.open("w", encoding="utf-8") as file:
        json.dump(
            value,
            file,
            ensure_ascii=False,
            indent=2,
        )


def safe_divide(
    numerator: np.ndarray,
    denominator: np.ndarray,
) -> np.ndarray:
    result = np.full(
        np.broadcast_shapes(
            np.shape(numerator),
            np.shape(denominator),
        ),
        np.nan,
        dtype=np.float64,
    )

    np.divide(
        numerator,
        denominator,
        out=result,
        where=np.asarray(denominator) > 0,
    )

    return result


def safe_scalar_ratio(
    numerator: float,
    denominator: float,
) -> float:
    if not np.isfinite(denominator) or abs(denominator) <= 0:
        return np.nan

    return float(numerator / denominator)


def percentile_interval(
    values: np.ndarray,
) -> Tuple[float, float]:
    finite = np.asarray(values, dtype=np.float64)
    finite = finite[np.isfinite(finite)]

    if len(finite) == 0:
        return np.nan, np.nan

    alpha = 1.0 - CI_LEVEL

    return (
        float(np.quantile(finite, alpha / 2.0)),
        float(np.quantile(finite, 1.0 - alpha / 2.0)),
    )


def stable_conclusion(
    difference_ci_low: float,
    difference_ci_high: float,
) -> str:
    if (
        np.isfinite(difference_ci_high)
        and difference_ci_high < 0
    ):
        return "Candidate_stably_better"

    if (
        np.isfinite(difference_ci_low)
        and difference_ci_low > 0
    ):
        return "Reference_stably_better"

    return "No_stable_difference"


def ensure_required_files() -> None:
    required = [
        STEP01_METHOD_FILE,
        STEP01_MANIFEST_FILE,
        STEP02_METHOD_FILE,
        STEP02_OVERALL_FILE,
        STEP02_FOLD_FILE,
        STEP02_MANIFEST_FILE,
        *ALIGNED_FILES.values(),
    ]

    missing = [
        str(path)
        for path in required
        if not path.exists()
    ]

    if missing:
        raise FileNotFoundError(
            "Required locked inputs are missing:\n"
            + "\n".join(missing)
        )


# =============================================================================
# Input integrity and bootstrap design
# =============================================================================

def verify_locked_inputs() -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    step01_method = read_json(STEP01_METHOD_FILE)
    step02_method = read_json(STEP02_METHOD_FILE)

    step01_version = str(
        step01_method.get("Code_Version", "")
    )
    step02_version = str(
        step02_method.get("Code_Version", "")
    )

    rows.append(
        {
            "Check": "Step01_Code_Version",
            "Observed": step01_version,
            "Expected": EXPECTED_STEP01_VERSION,
            "Passed": step01_version == EXPECTED_STEP01_VERSION,
        }
    )
    rows.append(
        {
            "Check": "Step02_Code_Version",
            "Observed": step02_version,
            "Expected": EXPECTED_STEP02_VERSION,
            "Passed": step02_version == EXPECTED_STEP02_VERSION,
        }
    )

    step01_manifest = pd.read_csv(STEP01_MANIFEST_FILE)

    for validation_scheme, path in ALIGNED_FILES.items():
        actual_hash = sha256_file(path)

        manifest_row = step01_manifest.loc[
            step01_manifest[
                "Validation_Scheme"
            ].astype(str) == validation_scheme
        ]

        manifest_hash = (
            str(manifest_row.iloc[0]["SHA256"])
            if len(manifest_row) == 1
            else ""
        )

        rows.append(
            {
                "Check": (
                    f"{validation_scheme}_Aligned_SHA256_"
                    "Matches_Step01_Manifest"
                ),
                "Observed": actual_hash,
                "Expected": manifest_hash,
                "Passed": actual_hash == manifest_hash,
            }
        )

    step02_manifest = pd.read_csv(STEP02_MANIFEST_FILE)

    for filename, path in [
        (
            "02_Overall_Unified_Prediction_Metrics.csv",
            STEP02_OVERALL_FILE,
        ),
        (
            "03_Fold_Level_Unified_Prediction_Metrics.csv",
            STEP02_FOLD_FILE,
        ),
    ]:
        manifest_row = step02_manifest.loc[
            step02_manifest["File"].astype(str) == filename
        ]

        expected_hash = (
            str(manifest_row.iloc[0]["SHA256"])
            if len(manifest_row) == 1
            else ""
        )
        actual_hash = sha256_file(path)

        rows.append(
            {
                "Check": f"{filename}_SHA256",
                "Observed": actual_hash,
                "Expected": expected_hash,
                "Passed": actual_hash == expected_hash,
            }
        )

    result = pd.DataFrame(rows)

    if not result["Passed"].all():
        result.to_csv(
            OUTPUT_ROOT / "ERROR_Input_Integrity_Audit.csv",
            index=False,
            encoding="utf-8-sig",
        )
        raise ValueError(
            "Locked Step 01 or Step 02 input integrity check failed."
        )

    return result


def aligned_use_columns() -> List[str]:
    columns = [
        "GRID_UID",
        "Country",
        "Year",
        "Season",
        "Spatial_Block",
        "Validation_Fold",
        "Count_Response",
        "Observed_Count",
        "Observed_Rate",
    ]

    for model in MODELS:
        columns.extend(
            [
                f"{model}_Predicted_Count",
                f"{model}_Predicted_Rate",
                (
                    f"{model}_Predicted_"
                    "Positive_Probability"
                ),
                (
                    f"{model}_Predicted_"
                    "Conditional_Positive_Count"
                ),
                (
                    f"{model}_Predicted_"
                    "Conditional_Positive_Rate"
                ),
            ]
        )

    return columns


def read_aligned(validation_scheme: str) -> pd.DataFrame:
    path = ALIGNED_FILES[validation_scheme]
    header = pd.read_csv(path, nrows=0)
    required = aligned_use_columns()

    missing = sorted(set(required) - set(header.columns))

    if missing:
        raise ValueError(
            f"{validation_scheme} aligned OOF is missing columns:\n"
            + "\n".join(missing)
        )

    data = pd.read_csv(
        path,
        usecols=required,
        dtype={
            "GRID_UID": str,
            "Country": str,
            "Count_Response": str,
        },
    )

    if len(data) != EXPECTED_ROWS_PER_SCHEME:
        raise ValueError(
            f"{validation_scheme} has {len(data):,} rows; "
            f"expected {EXPECTED_ROWS_PER_SCHEME:,}."
        )

    if data["GRID_UID"].nunique() != EXPECTED_GRID_COUNT:
        raise ValueError(
            f"{validation_scheme} does not contain "
            f"{EXPECTED_GRID_COUNT:,} grids."
        )

    if data.isna().any().any():
        missing_columns = (
            data.columns[data.isna().any()].tolist()
        )
        raise ValueError(
            f"{validation_scheme} has missing required values in: "
            + ", ".join(missing_columns)
        )

    return data


def build_grid_metadata(
    temporal_data: pd.DataFrame,
) -> pd.DataFrame:
    mapping = temporal_data[
        ["GRID_UID", "Country", "Spatial_Block"]
    ].drop_duplicates()

    duplicated = mapping.duplicated(
        "GRID_UID",
        keep=False,
    )

    if duplicated.any():
        mapping.loc[duplicated].to_csv(
            OUTPUT_ROOT / "ERROR_Grid_Metadata_Duplicates.csv",
            index=False,
            encoding="utf-8-sig",
        )
        raise ValueError(
            "GRID_UID does not have a unique Country/Spatial_Block mapping."
        )

    mapping["Spatial_Block"] = (
        mapping["Spatial_Block"].astype(int)
    )

    mapping = mapping.sort_values(
        "GRID_UID"
    ).reset_index(drop=True)

    if len(mapping) != EXPECTED_GRID_COUNT:
        raise ValueError(
            "Grid metadata does not contain the locked 4,982 grids."
        )

    mapping["Bootstrap_Stratum"] = (
        mapping["Country"].astype(str)
        + "__Block_"
        + mapping["Spatial_Block"].astype(str)
    )
    mapping["Grid_Index"] = np.arange(
        len(mapping),
        dtype=np.int32,
    )

    return mapping


def build_stratified_bootstrap_counts(
    grid_metadata: pd.DataFrame,
) -> Tuple[np.ndarray, pd.DataFrame, pd.DataFrame]:
    rng = np.random.default_rng(
        BOOTSTRAP_RANDOM_SEED
    )

    counts = np.zeros(
        (
            BOOTSTRAP_REPLICATES,
            len(grid_metadata),
        ),
        dtype=np.int16,
    )

    stratum_rows: List[Dict[str, object]] = []

    for stratum, group in grid_metadata.groupby(
        "Bootstrap_Stratum",
        sort=True,
    ):
        indices = group[
            "Grid_Index"
        ].to_numpy(dtype=np.int32)

        stratum_n = len(indices)

        draws = rng.multinomial(
            n=stratum_n,
            pvals=np.full(
                stratum_n,
                1.0 / stratum_n,
                dtype=np.float64,
            ),
            size=BOOTSTRAP_REPLICATES,
        )

        if draws.max() > np.iinfo(np.int16).max:
            raise OverflowError(
                "Bootstrap multiplicity exceeded int16 capacity."
            )

        counts[:, indices] = draws.astype(
            np.int16,
            copy=False,
        )

        replicate_totals = counts[
            :, indices
        ].sum(axis=1)

        stratum_rows.append(
            {
                "Bootstrap_Stratum": stratum,
                "Country": str(group["Country"].iloc[0]),
                "Spatial_Block": int(
                    group["Spatial_Block"].iloc[0]
                ),
                "Grid_Count": int(stratum_n),
                "Replicate_Min_Selected_Grid_Draws": int(
                    replicate_totals.min()
                ),
                "Replicate_Max_Selected_Grid_Draws": int(
                    replicate_totals.max()
                ),
                "Expected_Draws_Per_Replicate": int(
                    stratum_n
                ),
                "All_Replicates_Preserve_Stratum_Size": bool(
                    np.all(replicate_totals == stratum_n)
                ),
            }
        )

    replicate_total = counts.sum(axis=1)

    replicate_qa = pd.DataFrame(
        {
            "Bootstrap_Replicate": np.arange(
                1,
                BOOTSTRAP_REPLICATES + 1,
                dtype=np.int32,
            ),
            "Total_Grid_Draws": replicate_total.astype(
                np.int32
            ),
            "Unique_Grid_Count_Selected": np.count_nonzero(
                counts,
                axis=1,
            ).astype(np.int32),
            "Maximum_Grid_Multiplicity": counts.max(
                axis=1
            ).astype(np.int32),
        }
    )

    if not np.all(
        replicate_total == EXPECTED_GRID_COUNT
    ):
        raise ValueError(
            "Bootstrap replicates do not preserve total grid draws."
        )

    stratum_qa = pd.DataFrame(stratum_rows)

    if not stratum_qa[
        "All_Replicates_Preserve_Stratum_Size"
    ].all():
        raise ValueError(
            "One or more Country × Spatial_Block strata "
            "were not preserved."
        )

    return counts, stratum_qa, replicate_qa


# =============================================================================
# GRID_UID-level sufficient statistics
# =============================================================================

def aggregate_by_grid(
    grid_index: np.ndarray,
    values: np.ndarray,
    grid_count: int,
) -> np.ndarray:
    return np.bincount(
        grid_index,
        weights=np.asarray(values, dtype=np.float64),
        minlength=grid_count,
    ).astype(np.float64, copy=False)


def build_group_statistics(
    group: pd.DataFrame,
    grid_metadata: pd.DataFrame,
) -> Tuple[
    np.ndarray,
    Dict[str, Dict[str, np.ndarray]],
    Dict[str, Dict[str, float]],
]:
    grid_lookup = pd.Series(
        grid_metadata[
            "Grid_Index"
        ].to_numpy(dtype=np.int32),
        index=grid_metadata["GRID_UID"].astype(str),
    )

    mapped = group["GRID_UID"].astype(str).map(
        grid_lookup
    )

    if mapped.isna().any():
        raise ValueError(
            "A group contains GRID_UID values outside the locked universe."
        )

    grid_index = mapped.to_numpy(dtype=np.int32)
    grid_count = len(grid_metadata)

    observed_count = group[
        "Observed_Count"
    ].to_numpy(dtype=np.float64)
    observed_rate = group[
        "Observed_Rate"
    ].to_numpy(dtype=np.float64)
    positive = observed_count > 0

    n_by_grid = aggregate_by_grid(
        grid_index,
        np.ones(len(group), dtype=np.float64),
        grid_count,
    )
    positive_n_by_grid = aggregate_by_grid(
        grid_index,
        positive.astype(np.float64),
        grid_count,
    )

    if np.count_nonzero(n_by_grid) != EXPECTED_GRID_COUNT:
        raise ValueError(
            "A season-response group does not contain all 4,982 grids."
        )

    model_statistics: Dict[
        str,
        Dict[str, np.ndarray],
    ] = {}
    point_metrics: Dict[
        str,
        Dict[str, float],
    ] = {}

    for model in MODELS:
        predicted_count = group[
            f"{model}_Predicted_Count"
        ].to_numpy(dtype=np.float64)
        predicted_rate = group[
            f"{model}_Predicted_Rate"
        ].to_numpy(dtype=np.float64)
        probability = group[
            f"{model}_Predicted_Positive_Probability"
        ].to_numpy(dtype=np.float64)
        conditional_count = group[
            (
                f"{model}_Predicted_"
                "Conditional_Positive_Count"
            )
        ].to_numpy(dtype=np.float64)
        conditional_rate = group[
            (
                f"{model}_Predicted_"
                "Conditional_Positive_Rate"
            )
        ].to_numpy(dtype=np.float64)

        count_error = predicted_count - observed_count
        rate_error = predicted_rate - observed_rate
        occurrence_error = (
            probability - positive.astype(np.float64)
        )

        conditional_count_error = (
            conditional_count - observed_count
        )
        conditional_rate_error = (
            conditional_rate - observed_rate
        )

        statistics = {
            "Rate_SSE": aggregate_by_grid(
                grid_index,
                np.square(rate_error),
                grid_count,
            ),
            "Rate_SAE": aggregate_by_grid(
                grid_index,
                np.abs(rate_error),
                grid_count,
            ),
            "Rate_Error_Sum": aggregate_by_grid(
                grid_index,
                rate_error,
                grid_count,
            ),
            "Count_SSE": aggregate_by_grid(
                grid_index,
                np.square(count_error),
                grid_count,
            ),
            "Count_SAE": aggregate_by_grid(
                grid_index,
                np.abs(count_error),
                grid_count,
            ),
            "Count_Error_Sum": aggregate_by_grid(
                grid_index,
                count_error,
                grid_count,
            ),
            "Occurrence_Brier_Sum": aggregate_by_grid(
                grid_index,
                np.square(occurrence_error),
                grid_count,
            ),
            "Occurrence_Error_Sum": aggregate_by_grid(
                grid_index,
                occurrence_error,
                grid_count,
            ),
            "Positive_Conditional_Rate_SSE": aggregate_by_grid(
                grid_index,
                np.where(
                    positive,
                    np.square(conditional_rate_error),
                    0.0,
                ),
                grid_count,
            ),
            "Positive_Conditional_Rate_SAE": aggregate_by_grid(
                grid_index,
                np.where(
                    positive,
                    np.abs(conditional_rate_error),
                    0.0,
                ),
                grid_count,
            ),
            "Positive_Conditional_Count_SSE": aggregate_by_grid(
                grid_index,
                np.where(
                    positive,
                    np.square(conditional_count_error),
                    0.0,
                ),
                grid_count,
            ),
            "Positive_Conditional_Count_SAE": aggregate_by_grid(
                grid_index,
                np.where(
                    positive,
                    np.abs(conditional_count_error),
                    0.0,
                ),
                grid_count,
            ),
        }

        model_statistics[model] = statistics

        n_total = float(n_by_grid.sum())
        positive_total = float(
            positive_n_by_grid.sum()
        )

        point_metrics[model] = {
            "Rate_RMSE": float(
                np.sqrt(
                    statistics["Rate_SSE"].sum()
                    / n_total
                )
            ),
            "Rate_MAE": float(
                statistics["Rate_SAE"].sum()
                / n_total
            ),
            "Count_RMSE": float(
                np.sqrt(
                    statistics["Count_SSE"].sum()
                    / n_total
                )
            ),
            "Count_MAE": float(
                statistics["Count_SAE"].sum()
                / n_total
            ),
            "Occurrence_Brier_Score": float(
                statistics[
                    "Occurrence_Brier_Sum"
                ].sum()
                / n_total
            ),
            "Positive_Conditional_Rate_RMSE": float(
                np.sqrt(
                    statistics[
                        "Positive_Conditional_Rate_SSE"
                    ].sum()
                    / positive_total
                )
            ),
            "Positive_Conditional_Rate_MAE": float(
                statistics[
                    "Positive_Conditional_Rate_SAE"
                ].sum()
                / positive_total
            ),
            "Positive_Conditional_Count_RMSE": float(
                np.sqrt(
                    statistics[
                        "Positive_Conditional_Count_SSE"
                    ].sum()
                    / positive_total
                )
            ),
            "Positive_Conditional_Count_MAE": float(
                statistics[
                    "Positive_Conditional_Count_SAE"
                ].sum()
                / positive_total
            ),
            "Rate_Absolute_Mean_Bias": float(
                abs(
                    statistics["Rate_Error_Sum"].sum()
                    / n_total
                )
            ),
            "Count_Absolute_Mean_Bias": float(
                abs(
                    statistics["Count_Error_Sum"].sum()
                    / n_total
                )
            ),
            "Occurrence_Absolute_Mean_Bias": float(
                abs(
                    statistics[
                        "Occurrence_Error_Sum"
                    ].sum()
                    / n_total
                )
            ),
        }

    return (
        np.column_stack(
            [
                n_by_grid,
                positive_n_by_grid,
            ]
        ),
        model_statistics,
        point_metrics,
    )


def calculate_bootstrap_model_metrics(
    bootstrap_counts_float: np.ndarray,
    denominators_by_grid: np.ndarray,
    model_statistics: Mapping[
        str,
        Mapping[str, np.ndarray],
    ],
) -> Dict[str, Dict[str, np.ndarray]]:
    n_by_grid = denominators_by_grid[:, 0]
    positive_n_by_grid = denominators_by_grid[:, 1]

    row_n = (
        bootstrap_counts_float @ n_by_grid
    )
    positive_n = (
        bootstrap_counts_float @ positive_n_by_grid
    )

    if np.any(row_n <= 0):
        raise ValueError(
            "A bootstrap replicate has no observations."
        )

    if np.any(positive_n <= 0):
        raise ValueError(
            "A bootstrap replicate has no positive observations."
        )

    output: Dict[
        str,
        Dict[str, np.ndarray],
    ] = {}

    for model in MODELS:
        statistics = model_statistics[model]

        names = list(statistics)
        statistic_matrix = np.column_stack(
            [statistics[name] for name in names]
        )

        totals = (
            bootstrap_counts_float @ statistic_matrix
        )

        total_by_name = {
            name: totals[:, index]
            for index, name in enumerate(names)
        }

        output[model] = {
            "Rate_RMSE": np.sqrt(
                safe_divide(
                    total_by_name["Rate_SSE"],
                    row_n,
                )
            ),
            "Rate_MAE": safe_divide(
                total_by_name["Rate_SAE"],
                row_n,
            ),
            "Count_RMSE": np.sqrt(
                safe_divide(
                    total_by_name["Count_SSE"],
                    row_n,
                )
            ),
            "Count_MAE": safe_divide(
                total_by_name["Count_SAE"],
                row_n,
            ),
            "Occurrence_Brier_Score": safe_divide(
                total_by_name[
                    "Occurrence_Brier_Sum"
                ],
                row_n,
            ),
            "Positive_Conditional_Rate_RMSE": np.sqrt(
                safe_divide(
                    total_by_name[
                        "Positive_Conditional_Rate_SSE"
                    ],
                    positive_n,
                )
            ),
            "Positive_Conditional_Rate_MAE": safe_divide(
                total_by_name[
                    "Positive_Conditional_Rate_SAE"
                ],
                positive_n,
            ),
            "Positive_Conditional_Count_RMSE": np.sqrt(
                safe_divide(
                    total_by_name[
                        "Positive_Conditional_Count_SSE"
                    ],
                    positive_n,
                )
            ),
            "Positive_Conditional_Count_MAE": safe_divide(
                total_by_name[
                    "Positive_Conditional_Count_SAE"
                ],
                positive_n,
            ),
            "Rate_Absolute_Mean_Bias": np.abs(
                safe_divide(
                    total_by_name["Rate_Error_Sum"],
                    row_n,
                )
            ),
            "Count_Absolute_Mean_Bias": np.abs(
                safe_divide(
                    total_by_name["Count_Error_Sum"],
                    row_n,
                )
            ),
            "Occurrence_Absolute_Mean_Bias": np.abs(
                safe_divide(
                    total_by_name[
                        "Occurrence_Error_Sum"
                    ],
                    row_n,
                )
            ),
        }

    return output


# =============================================================================
# Point-estimate, fold and descriptive audits
# =============================================================================

def expected_step02_metric(
    step02_row: pd.Series,
    metric: str,
) -> float:
    if metric == "Rate_Absolute_Mean_Bias":
        return float(abs(step02_row["Rate_Mean_Bias"]))

    if metric == "Count_Absolute_Mean_Bias":
        return float(abs(step02_row["Count_Mean_Bias"]))

    if metric == "Occurrence_Absolute_Mean_Bias":
        return float(
            abs(step02_row["Occurrence_Mean_Bias"])
        )

    return float(step02_row[metric])


def build_descriptive_nonadditive_differences(
    step02_overall: pd.DataFrame,
) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []

    for (
        validation_scheme,
        season,
        response,
    ), group in step02_overall.groupby(
        [
            "Validation_Scheme",
            "Season",
            "Count_Response",
        ],
        sort=True,
    ):
        indexed = group.set_index("Model")

        for (
            pair_name,
            candidate,
            reference,
        ) in MODEL_PAIRS:
            for (
                metric,
                direction,
            ) in NONADDITIVE_DESCRIPTIVE_METRICS.items():
                candidate_value = float(
                    indexed.loc[candidate, metric]
                )
                reference_value = float(
                    indexed.loc[reference, metric]
                )
                difference = (
                    candidate_value - reference_value
                )

                candidate_better = (
                    difference > 0
                    if direction == "Higher"
                    else difference < 0
                )

                rows.append(
                    {
                        "Validation_Scheme": validation_scheme,
                        "Season": int(season),
                        "Season_Label": SEASONS[int(season)],
                        "Count_Response": response,
                        "Model_Pair": pair_name,
                        "Candidate_Model": candidate,
                        "Reference_Model": reference,
                        "Metric": metric,
                        "Preferred_Direction": direction,
                        "Candidate_Value": candidate_value,
                        "Reference_Value": reference_value,
                        "Candidate_Minus_Reference": difference,
                        "Candidate_Better_Descriptively": bool(
                            candidate_better
                        ),
                        "Bootstrap_CI_Available": False,
                        "Reason_No_Bootstrap_CI": (
                            "This metric is rank-, threshold-, or "
                            "calibration-structure dependent and is "
                            "retained as a locked Step-02 descriptive "
                            "difference rather than mixed with the "
                            "exact sufficient-statistic bootstrap."
                        ),
                    }
                )

    return pd.DataFrame(rows)


def build_fold_win_counts(
    step02_fold: pd.DataFrame,
) -> pd.DataFrame:
    data = step02_fold.copy()

    data["Rate_Absolute_Mean_Bias"] = (
        data["Rate_Mean_Bias"].abs()
    )
    data["Count_Absolute_Mean_Bias"] = (
        data["Count_Mean_Bias"].abs()
    )
    data["Occurrence_Absolute_Mean_Bias"] = (
        data["Occurrence_Mean_Bias"].abs()
    )

    rows: List[Dict[str, object]] = []

    for (
        validation_scheme,
        season,
        response,
    ), group in data.groupby(
        [
            "Validation_Scheme",
            "Season",
            "Count_Response",
        ],
        sort=True,
    ):
        for (
            pair_name,
            candidate,
            reference,
        ) in MODEL_PAIRS:
            candidate_rows = (
                group.loc[group["Model"] == candidate]
                .set_index("Validation_Fold")
            )
            reference_rows = (
                group.loc[group["Model"] == reference]
                .set_index("Validation_Fold")
            )

            common_folds = sorted(
                set(candidate_rows.index)
                & set(reference_rows.index)
            )

            for metric in BOOTSTRAP_METRICS:
                candidate_values = candidate_rows.loc[
                    common_folds,
                    metric,
                ].to_numpy(dtype=np.float64)
                reference_values = reference_rows.loc[
                    common_folds,
                    metric,
                ].to_numpy(dtype=np.float64)

                valid = (
                    np.isfinite(candidate_values)
                    & np.isfinite(reference_values)
                )

                difference = (
                    candidate_values[valid]
                    - reference_values[valid]
                )

                tolerance = 1e-15

                rows.append(
                    {
                        "Validation_Scheme": validation_scheme,
                        "Season": int(season),
                        "Season_Label": SEASONS[int(season)],
                        "Count_Response": response,
                        "Model_Pair": pair_name,
                        "Candidate_Model": candidate,
                        "Reference_Model": reference,
                        "Metric": metric,
                        "Available_Fold_or_Block_N": int(
                            valid.sum()
                        ),
                        "Candidate_Better_N": int(
                            np.sum(difference < -tolerance)
                        ),
                        "Reference_Better_N": int(
                            np.sum(difference > tolerance)
                        ),
                        "Tie_N": int(
                            np.sum(
                                np.abs(difference) <= tolerance
                            )
                        ),
                        "Mean_Candidate_Minus_Reference": (
                            float(np.mean(difference))
                            if len(difference)
                            else np.nan
                        ),
                    }
                )

    return pd.DataFrame(rows)


# =============================================================================
# Main analysis
# =============================================================================

def main() -> int:
    if OUTPUT_ROOT.exists():
        shutil.rmtree(OUTPUT_ROOT)

    OUTPUT_ROOT.mkdir(
        parents=True,
        exist_ok=True,
    )
    LOG_FILE.write_text("", encoding="utf-8")

    log("Starting paired stratified GRID_UID-cluster bootstrap.")
    log(f"Step 03 code version: {CODE_VERSION}.")
    log(
        "No model is fitted, tuned, selected, or predicted by this script."
    )
    log(
        f"Bootstrap replicates: {BOOTSTRAP_REPLICATES:,}; "
        "cluster: GRID_UID; strata: Country × Spatial_Block."
    )
    log(
        "The same bootstrap grid multiplicities are used for all models, "
        "seasons, responses, and both validation schemes."
    )

    ensure_required_files()
    input_audit = verify_locked_inputs()

    step02_overall = pd.read_csv(
        STEP02_OVERALL_FILE
    )
    step02_fold = pd.read_csv(
        STEP02_FOLD_FILE
    )

    expected_overall_rows = (
        len(ALIGNED_FILES)
        * len(SEASONS)
        * len(RESPONSES)
        * len(MODELS)
    )

    if len(step02_overall) != expected_overall_rows:
        raise ValueError(
            "Step 02 overall metrics do not contain the "
            "expected 36 rows."
        )

    log("Reading Temporal aligned OOF and building locked grid metadata.")
    temporal_data = read_aligned("Temporal")
    grid_metadata = build_grid_metadata(
        temporal_data
    )

    (
        bootstrap_counts,
        stratum_qa,
        replicate_qa,
    ) = build_stratified_bootstrap_counts(
        grid_metadata
    )

    bootstrap_counts_hash = sha256_array(
        bootstrap_counts
    )
    bootstrap_counts_float = (
        bootstrap_counts.astype(
            np.float64,
            copy=False,
        )
    )

    log(
        "Built one shared stratified bootstrap multiplicity matrix: "
        f"{BOOTSTRAP_REPLICATES:,} × {EXPECTED_GRID_COUNT:,}; "
        f"SHA256={bootstrap_counts_hash}."
    )

    grid_metadata.to_csv(
        OUTPUT_ROOT / "Bootstrap_Grid_Metadata.csv",
        index=False,
        encoding="utf-8-sig",
    )

    summary_rows: List[Dict[str, object]] = []
    replicate_frames: List[pd.DataFrame] = []
    reproduction_rows: List[Dict[str, object]] = []
    combination_qa_rows: List[Dict[str, object]] = []

    for validation_scheme in [
        "Temporal",
        "Spatial",
    ]:
        if validation_scheme == "Temporal":
            data = temporal_data
        else:
            log("Reading Spatial aligned OOF.")
            data = read_aligned("Spatial")

            spatial_mapping = build_grid_metadata(
                data
            )

            metadata_columns = [
                "GRID_UID",
                "Country",
                "Spatial_Block",
                "Bootstrap_Stratum",
            ]

            if not spatial_mapping[
                metadata_columns
            ].equals(
                grid_metadata[metadata_columns]
            ):
                raise ValueError(
                    "Temporal and Spatial grid metadata are not identical."
                )

        for season, season_label in SEASONS.items():
            for response in RESPONSES:
                group = data.loc[
                    (
                        data["Season"].astype(int)
                        == int(season)
                    )
                    & (
                        data["Count_Response"].astype(str)
                        == response
                    )
                ].copy()

                if len(group) != EXPECTED_ROWS_PER_COMBINATION:
                    raise ValueError(
                        f"{validation_scheme}, {season_label}, "
                        f"{response} has {len(group):,} rows; "
                        f"expected {EXPECTED_ROWS_PER_COMBINATION:,}."
                    )

                log(
                    f"Bootstrap: {validation_scheme}, "
                    f"{season_label}, {response}."
                )

                (
                    denominators_by_grid,
                    model_statistics,
                    point_metrics,
                ) = build_group_statistics(
                    group=group,
                    grid_metadata=grid_metadata,
                )

                bootstrap_metrics = (
                    calculate_bootstrap_model_metrics(
                        bootstrap_counts_float=(
                            bootstrap_counts_float
                        ),
                        denominators_by_grid=(
                            denominators_by_grid
                        ),
                        model_statistics=model_statistics,
                    )
                )

                combination_qa_rows.append(
                    {
                        "Validation_Scheme": validation_scheme,
                        "Season": int(season),
                        "Season_Label": season_label,
                        "Count_Response": response,
                        "Rows": int(len(group)),
                        "GRID_UID_Count": int(
                            group["GRID_UID"].nunique()
                        ),
                        "Year_Count": int(
                            group["Year"].nunique()
                        ),
                        "Observed_Positive_N": int(
                            (group["Observed_Count"] > 0).sum()
                        ),
                        "Bootstrap_Replicates": int(
                            BOOTSTRAP_REPLICATES
                        ),
                        "Bootstrap_Count_Matrix_SHA256": (
                            bootstrap_counts_hash
                        ),
                    }
                )

                # Reproduce the locked Step 02 point estimates.
                for model in MODELS:
                    formal_row = step02_overall.loc[
                        (
                            step02_overall[
                                "Validation_Scheme"
                            ].astype(str)
                            == validation_scheme
                        )
                        & (
                            step02_overall[
                                "Season"
                            ].astype(int)
                            == int(season)
                        )
                        & (
                            step02_overall[
                                "Count_Response"
                            ].astype(str)
                            == response
                        )
                        & (
                            step02_overall[
                                "Model"
                            ].astype(str)
                            == model
                        )
                    ]

                    if len(formal_row) != 1:
                        raise ValueError(
                            "Could not identify one locked Step 02 "
                            "point-metric row."
                        )

                    formal_row = formal_row.iloc[0]

                    for metric in BOOTSTRAP_METRICS:
                        recalculated = float(
                            point_metrics[model][metric]
                        )
                        expected = expected_step02_metric(
                            formal_row,
                            metric,
                        )
                        absolute_difference = abs(
                            recalculated - expected
                        )
                        passed = bool(
                            np.isclose(
                                recalculated,
                                expected,
                                atol=NUMERIC_ATOL,
                                rtol=NUMERIC_RTOL,
                            )
                        )

                        reproduction_rows.append(
                            {
                                "Validation_Scheme": validation_scheme,
                                "Season": int(season),
                                "Season_Label": season_label,
                                "Count_Response": response,
                                "Model": model,
                                "Metric": metric,
                                "Step02_Value": expected,
                                "Recalculated_Value": recalculated,
                                "Absolute_Difference": absolute_difference,
                                "Passed": passed,
                            }
                        )

                for (
                    pair_name,
                    candidate,
                    reference,
                ) in MODEL_PAIRS:
                    replicate_frame = pd.DataFrame(
                        {
                            "Validation_Scheme": validation_scheme,
                            "Season": int(season),
                            "Season_Label": season_label,
                            "Count_Response": response,
                            "Model_Pair": pair_name,
                            "Candidate_Model": candidate,
                            "Reference_Model": reference,
                            "Bootstrap_Replicate": np.arange(
                                1,
                                BOOTSTRAP_REPLICATES + 1,
                                dtype=np.int32,
                            ),
                        }
                    )

                    for metric in BOOTSTRAP_METRICS:
                        candidate_values = (
                            bootstrap_metrics[
                                candidate
                            ][metric]
                        )
                        reference_values = (
                            bootstrap_metrics[
                                reference
                            ][metric]
                        )

                        difference = (
                            candidate_values
                            - reference_values
                        )
                        percent_improvement = (
                            100.0
                            * safe_divide(
                                (
                                    reference_values
                                    - candidate_values
                                ),
                                np.abs(reference_values),
                            )
                        )

                        replicate_frame[
                            f"{metric}_Difference"
                        ] = difference
                        replicate_frame[
                            f"{metric}_Percent_Improvement"
                        ] = percent_improvement

                        finite = np.isfinite(difference)
                        valid_difference = difference[finite]

                        difference_ci_low, difference_ci_high = (
                            percentile_interval(valid_difference)
                        )
                        (
                            improvement_ci_low,
                            improvement_ci_high,
                        ) = percentile_interval(
                            percent_improvement
                        )

                        point_candidate = float(
                            point_metrics[candidate][metric]
                        )
                        point_reference = float(
                            point_metrics[reference][metric]
                        )
                        point_difference = (
                            point_candidate
                            - point_reference
                        )
                        point_improvement = (
                            100.0
                            * safe_scalar_ratio(
                                (
                                    point_reference
                                    - point_candidate
                                ),
                                abs(point_reference),
                            )
                        )

                        summary_rows.append(
                            {
                                "Validation_Scheme": validation_scheme,
                                "Season": int(season),
                                "Season_Label": season_label,
                                "Count_Response": response,
                                "Model_Pair": pair_name,
                                "Candidate_Model": candidate,
                                "Reference_Model": reference,
                                "Metric": metric,
                                "Preferred_Direction": "Lower",
                                "Candidate_Point_Estimate": point_candidate,
                                "Reference_Point_Estimate": point_reference,
                                "Candidate_Minus_Reference": point_difference,
                                "Percent_Improvement_Positive_Is_Better": (
                                    point_improvement
                                ),
                                "Bootstrap_Replicates_Requested": int(
                                    BOOTSTRAP_REPLICATES
                                ),
                                "Bootstrap_Replicates_Valid": int(
                                    finite.sum()
                                ),
                                "Bootstrap_Difference_Mean": float(
                                    np.mean(valid_difference)
                                ),
                                "Bootstrap_Difference_Median": float(
                                    np.median(valid_difference)
                                ),
                                "Bootstrap_Difference_SE": float(
                                    np.std(
                                        valid_difference,
                                        ddof=1,
                                    )
                                ),
                                "Difference_CI_Level": float(
                                    CI_LEVEL
                                ),
                                "Difference_CI_Lower": (
                                    difference_ci_low
                                ),
                                "Difference_CI_Upper": (
                                    difference_ci_high
                                ),
                                "Percent_Improvement_CI_Lower": (
                                    improvement_ci_low
                                ),
                                "Percent_Improvement_CI_Upper": (
                                    improvement_ci_high
                                ),
                                "Probability_Candidate_Better": float(
                                    np.mean(
                                        valid_difference < 0
                                    )
                                ),
                                "Probability_Reference_Better": float(
                                    np.mean(
                                        valid_difference > 0
                                    )
                                ),
                                "Probability_Exact_Tie": float(
                                    np.mean(
                                        valid_difference == 0
                                    )
                                ),
                                "CI_Excludes_Zero": bool(
                                    (
                                        difference_ci_high < 0
                                    )
                                    or (
                                        difference_ci_low > 0
                                    )
                                ),
                                "Stable_Conclusion": stable_conclusion(
                                    difference_ci_low,
                                    difference_ci_high,
                                ),
                            }
                        )

                    replicate_frames.append(
                        replicate_frame
                    )

        if validation_scheme == "Temporal":
            del data
            del temporal_data
        else:
            del data

    reproduction_audit = pd.DataFrame(
        reproduction_rows
    )

    if not reproduction_audit["Passed"].all():
        reproduction_audit.to_csv(
            OUTPUT_ROOT
            / "ERROR_Point_Estimate_Reproduction_Audit.csv",
            index=False,
            encoding="utf-8-sig",
        )
        raise ValueError(
            "Step 03 point estimates do not reproduce Step 02."
        )

    summary = pd.DataFrame(summary_rows)
    replicates = pd.concat(
        replicate_frames,
        ignore_index=True,
    )

    expected_summary_rows = (
        len(ALIGNED_FILES)
        * len(SEASONS)
        * len(RESPONSES)
        * len(MODEL_PAIRS)
        * len(BOOTSTRAP_METRICS)
    )
    expected_replicate_rows = (
        len(ALIGNED_FILES)
        * len(SEASONS)
        * len(RESPONSES)
        * len(MODEL_PAIRS)
        * BOOTSTRAP_REPLICATES
    )

    if len(summary) != expected_summary_rows:
        raise ValueError(
            "Unexpected paired-bootstrap summary row count."
        )

    if len(replicates) != expected_replicate_rows:
        raise ValueError(
            "Unexpected bootstrap replicate row count."
        )

    fold_win_counts = build_fold_win_counts(
        step02_fold
    )
    descriptive_nonadditive = (
        build_descriptive_nonadditive_differences(
            step02_overall
        )
    )

    stable_win_summary = (
        summary.groupby(
            [
                "Model_Pair",
                "Candidate_Model",
                "Reference_Model",
                "Metric",
            ],
            sort=True,
        )
        .agg(
            Comparison_N=(
                "Stable_Conclusion",
                "size",
            ),
            Candidate_Stably_Better_N=(
                "Stable_Conclusion",
                lambda values: int(
                    np.sum(
                        values
                        == "Candidate_stably_better"
                    )
                ),
            ),
            Reference_Stably_Better_N=(
                "Stable_Conclusion",
                lambda values: int(
                    np.sum(
                        values
                        == "Reference_stably_better"
                    )
                ),
            ),
            No_Stable_Difference_N=(
                "Stable_Conclusion",
                lambda values: int(
                    np.sum(
                        values
                        == "No_stable_difference"
                    )
                ),
            ),
            Point_Estimate_Candidate_Better_N=(
                "Candidate_Minus_Reference",
                lambda values: int(
                    np.sum(values < 0)
                ),
            ),
        )
        .reset_index()
    )

    metric_definition_rows = []

    for metric in BOOTSTRAP_METRICS:
        metric_definition_rows.append(
            {
                "Metric": metric,
                "Analysis_Role": (
                    "Primary exact paired GRID_UID-cluster "
                    "bootstrap metric"
                ),
                "Preferred_Direction": "Lower",
                "Bootstrap_CI": True,
                "Difference_Definition": (
                    "Candidate minus Reference"
                ),
                "Percent_Improvement_Definition": (
                    "100 × (Reference − Candidate) / "
                    "absolute(Reference); positive is better"
                ),
            }
        )

    for (
        metric,
        direction,
    ) in NONADDITIVE_DESCRIPTIVE_METRICS.items():
        metric_definition_rows.append(
            {
                "Metric": metric,
                "Analysis_Role": (
                    "Locked Step-02 descriptive paired difference"
                ),
                "Preferred_Direction": direction,
                "Bootstrap_CI": False,
                "Difference_Definition": (
                    "Candidate minus Reference"
                ),
                "Percent_Improvement_Definition": (
                    "Not calculated"
                ),
            }
        )

    metric_definitions = pd.DataFrame(
        metric_definition_rows
    )

    method = {
        "Step": "Model Comparison Step 03",
        "Code_Version": CODE_VERSION,
        "Created": datetime.now().isoformat(
            timespec="seconds"
        ),
        "Purpose": (
            "Estimate paired uncertainty in predictive-performance "
            "differences among Baseline NB1, Final Regression, and "
            "Final Hurdle RF."
        ),
        "No_Model_Fitting": True,
        "No_Model_Tuning": True,
        "No_Model_Selection": True,
        "No_New_Prediction": True,
        "Validation_Schemes_Analysed_Separately": [
            "Temporal",
            "Spatial",
        ],
        "Bootstrap": {
            "type": (
                "Paired nonparametric cluster bootstrap"
            ),
            "cluster_unit": "GRID_UID",
            "strata": [
                "Country",
                "Spatial_Block",
            ],
            "replicates": BOOTSTRAP_REPLICATES,
            "random_seed": BOOTSTRAP_RANDOM_SEED,
            "confidence_interval": (
                f"{CI_LEVEL:.0%} percentile interval"
            ),
            "all_years_within_selected_grid_retained": True,
            "same_grid_multiplicity_for_all_models": True,
            "same_grid_multiplicity_for_all_seasons_responses_and_validation_schemes": True,
            "bootstrap_count_matrix_sha256": (
                bootstrap_counts_hash
            ),
        },
        "Model_Pairs": [
            {
                "name": pair_name,
                "candidate": candidate,
                "reference": reference,
            }
            for (
                pair_name,
                candidate,
                reference,
            ) in MODEL_PAIRS
        ],
        "Primary_Bootstrap_Metrics": (
            BOOTSTRAP_METRICS
        ),
        "Difference_Sign": (
            "Candidate minus Reference. Because every primary "
            "bootstrap metric is lower-is-better, a negative "
            "difference favours the Candidate."
        ),
        "Stable_Conclusion_Rule": {
            "Candidate_stably_better": (
                "The full percentile CI is below zero."
            ),
            "Reference_stably_better": (
                "The full percentile CI is above zero."
            ),
            "No_stable_difference": (
                "The percentile CI includes zero."
            ),
        },
        "Nonadditive_Metric_Policy": {
            "metrics": list(
                NONADDITIVE_DESCRIPTIVE_METRICS
            ),
            "treatment": (
                "Point differences are imported from locked Step 02 "
                "and reported descriptively. They are not mixed with "
                "the exact sufficient-statistic bootstrap because "
                "rank-, threshold-, and calibration-structure metrics "
                "require a separate weighted-rank estimand."
            ),
        },
        "Interpretation_Limits": [
            (
                "A CI that includes zero is reported as no stable "
                "difference, not as proof of model equivalence."
            ),
            (
                "Temporal and Spatial validation results represent "
                "different generalisation tasks and are not pooled."
            ),
            (
                "Bootstrap comparisons quantify predictive "
                "performance differences and do not establish causal "
                "mechanisms."
            ),
        ],
    }

    # -------------------------------------------------------------------------
    # Write outputs
    # -------------------------------------------------------------------------

    write_json(
        OUTPUT_ROOT / "00_Method_Definition.json",
        method,
    )

    input_audit.to_csv(
        OUTPUT_ROOT / "01_Input_Integrity_Audit.csv",
        index=False,
        encoding="utf-8-sig",
    )

    reproduction_audit.to_csv(
        OUTPUT_ROOT
        / "02_Point_Estimate_Reproduction_Audit.csv",
        index=False,
        encoding="utf-8-sig",
    )

    summary.to_csv(
        OUTPUT_ROOT
        / "03_Paired_Bootstrap_Difference_Summary.csv",
        index=False,
        encoding="utf-8-sig",
    )

    replicates.to_csv(
        OUTPUT_ROOT
        / "04_Paired_Bootstrap_Replicate_Differences.csv.gz",
        index=False,
        compression="gzip",
    )

    fold_win_counts.to_csv(
        OUTPUT_ROOT
        / "05_Fold_Block_Win_Counts.csv",
        index=False,
        encoding="utf-8-sig",
    )

    descriptive_nonadditive.to_csv(
        OUTPUT_ROOT
        / "06_Descriptive_Nonadditive_Metric_Differences.csv",
        index=False,
        encoding="utf-8-sig",
    )

    stable_win_summary.to_csv(
        OUTPUT_ROOT
        / "07_Stable_Win_Count_Summary.csv",
        index=False,
        encoding="utf-8-sig",
    )

    stratum_qa.to_csv(
        OUTPUT_ROOT
        / "08_Bootstrap_Stratum_QA.csv",
        index=False,
        encoding="utf-8-sig",
    )

    replicate_qa.to_csv(
        OUTPUT_ROOT
        / "09_Bootstrap_Replicate_QA.csv",
        index=False,
        encoding="utf-8-sig",
    )

    pd.DataFrame(
        combination_qa_rows
    ).to_csv(
        OUTPUT_ROOT
        / "10_Season_Response_Bootstrap_QA.csv",
        index=False,
        encoding="utf-8-sig",
    )

    metric_definitions.to_csv(
        OUTPUT_ROOT
        / "11_Metric_Definitions.csv",
        index=False,
        encoding="utf-8-sig",
    )

    environment = {
        "Created": datetime.now().isoformat(
            timespec="seconds"
        ),
        "Code_Version": CODE_VERSION,
        "Python": sys.version,
        "Platform": platform.platform(),
        "NumPy": np.__version__,
        "pandas": pd.__version__,
        "SciPy": scipy.__version__,
        "scikit_learn": sklearn.__version__,
        "Bootstrap_Random_Generator": (
            "numpy.random.default_rng (PCG64)"
        ),
        "Bootstrap_Random_Seed": (
            BOOTSTRAP_RANDOM_SEED
        ),
        "Bootstrap_Count_Matrix_SHA256": (
            bootstrap_counts_hash
        ),
    }

    write_json(
        OUTPUT_ROOT / "Software_Environment.json",
        environment,
    )

    log(
        "Step 03 completed: paired stratified GRID_UID-cluster "
        "bootstrap confidence intervals were calculated for three "
        "locked model comparisons under Temporal and Spatial OOF "
        "without fitting, selecting, or predicting any model."
    )

    manifest_rows: List[Dict[str, object]] = []

    for path in sorted(OUTPUT_ROOT.iterdir()):
        if (
            path.is_file()
            and path.name != "12_Output_Manifest.csv"
        ):
            manifest_rows.append(
                {
                    "File": path.name,
                    "Relative_Path": path.name,
                    "File_Size_Bytes": int(
                        path.stat().st_size
                    ),
                    "SHA256": sha256_file(path),
                    "Step03_Code_Version": CODE_VERSION,
                }
            )

    pd.DataFrame(manifest_rows).to_csv(
        OUTPUT_ROOT / "12_Output_Manifest.csv",
        index=False,
        encoding="utf-8-sig",
    )

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception:
        error_text = traceback.format_exc()

        try:
            log("=" * 78)
            log("ERROR")
            log(error_text)
            log("=" * 78)
        except Exception:
            print(error_text, file=sys.stderr)

        raise
